### ISSUE TITLE
Add contributers name and Project owners name in the README.md

### ISSUE THREAD

**Issue by Ayush7614** [smv1999/CompetitiveProgrammingQuestionBank#10]
**Is your feature request related to a problem? Please describe.**
Add contributers name and Project owners name in the README.md

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/67006255/105854024-55c85b00-600c-11eb-81cb-f38000644c5a.png)

**Comment by Ayush7614** [comment]
Like this

**Comment by Ayush7614** [comment]
@smv1999 sir i have to work on the issue plss assign me

**Comment by smv1999** [comment]
Thank you for submitting this feature request issue. Sure @Ayush7614 ! You can start working on this.

**Comment by Ayush7614** [comment]
this is PR #12 for this issue plss review it sir

**Comment by smv1999** [comment]
Done @Ayush7614 ! I am closing this issue.
