### ISSUE TITLE
Add More question in numbers folder related to number

### ISSUE THREAD

**Issue by Ayush7614** [smv1999/CompetitiveProgrammingQuestionBank#11]
**Is your feature request related to a problem? Please describe.**
Add More question in numbers folder related to number

**Describe the solution you'd like**
Leap year or not
Prime number or not
Palindrome or not
Armstrong number or not
Strong number or not
Perfect number or not
Friendly pair or not (amicable or not)
Automorphic number or not
Harshad number or not
Abundant number or not
Power of a number
Factors of a number
Add two fractions

This are types of question i have to work on the issue plss assign me

**Comment by smv1999** [comment]
@Ayush7614 You can start working on this. Make sure to create a new folder inside Numbers called "Basic Programs" and add you code files inside that.

**Comment by Ayush7614** [comment]
Sure sir
