### ISSUE TITLE
Python code for Insertion sort , Quick sort in Sorting algorithms

### ISSUE THREAD

**Issue by dsrao711** [smv1999/CompetitiveProgrammingQuestionBank#113]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Python code for Insertion sort , Quick sort in Sorting algorithms

**Describe alternatives you've considered**

**Additional context**

**Comment by dsrao711** [comment]
Please assign me this issue

**Comment by smv1999** [comment]
Sure @dsrao711 , you can go ahead.
