### ISSUE TITLE
Create a separate folder for hackerrank problem solutions .

### ISSUE THREAD

**Issue by MannyP31** [smv1999/CompetitiveProgrammingQuestionBank#115]
Hello there , 
It's been well known that hackerrank has proved to be one of the most popular cp platform for developers.So I would just like to say that better to have a particular repo that just specifically contains all the hackerrank solutions so that it would be of great help to the programmers.Approve this issue of mine if you find this appropriate.

**Comment by smv1999** [comment]
I think it would make it redundant. This repo already brings everything related to Data Structures and Algorithms under one roof. It consists of problems mainly from HackerRank, Geeks for Geeks, LeetCode.

**Comment by MannyP31** [comment]
Yeah i know well . Your repo is an outstanding one and I appreciate that😊.I just wanted to say that what about having a separate folder for that and having the solutions  , shall I try doing that if you approve?

**Comment by smv1999** [comment]
Ohh I thought you were saying to create a separate repo for that!! If you wanna create a **new folder** specifically for HackerRank, you can very well go ahead.

**Comment by MannyP31** [comment]
Yeah exactly I was talking about the folder.Well I would look forward to contribute there .Thanks !!

**Comment by MannyP31** [comment]
I have written few js solutions of hackerrank for now. And I will regularly keep on updating them time to time. Shall I create a pull request now?

**Comment by smv1999** [comment]
Sure @MannyP31 !
