### ISSUE TITLE
Python Solution for merge intervals in dsa  450

### ISSUE THREAD

**Issue by dsrao711** [smv1999/CompetitiveProgrammingQuestionBank#116]
**Is your feature request related to a problem? Please describe.**

Link for the question :  https://leetcode.com/problems/merge-intervals/

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dsrao711** [comment]
Please assign me this issue

**Comment by smv1999** [comment]
Sure @dsrao711 , you can go ahead!

**Comment by MannyP31** [comment]
Shall I try solving that ? I guess previously someday I had already solved that after referring some tutorials.

**Comment by smv1999** [comment]
@dsrao711 is going with a solution in python already. Maybe you can solve the same problem in a different language.

**Comment by MannyP31** [comment]
okay sure!
