### ISSUE TITLE
Python solution for spiral matrix problem in dsa 450

### ISSUE THREAD

**Issue by dsrao711** [smv1999/CompetitiveProgrammingQuestionBank#119]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

Python solution for spiral matrix problem in dsa 450
Link to the problem : https://leetcode.com/problems/spiral-matrix/

**Additional context**

**Comment by dsrao711** [comment]
Please assign me this issue

**Comment by smv1999** [comment]
Sure @dsrao711 , you can go ahead !
