### ISSUE TITLE
To create a Hashing Directory for Hashing related problems

### ISSUE THREAD

**Issue by bishopmate** [smv1999/CompetitiveProgrammingQuestionBank#121]
I was unable to find a dedicated directory for Hashing Related problems which is also an Important Category in Competitve Programming and also in general. This is why I wanted to add a Hashing Directory and as a first step add this [problem](https://codeforces.com/contest/1527/problem/C) which requires using hashing to be solved. Do comment suggestions and give a thumbs up @smv1999 so I can code and then apply for a PR for the same.

**Comment by smv1999** [comment]
Sure @bishopmate , you can go ahead !
