### ISSUE TITLE
Python Solution for "Buy and sell stock" in dsa_450

### ISSUE THREAD

**Issue by dsrao711** [smv1999/CompetitiveProgrammingQuestionBank#123]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Link to the problem : https://leetcode.com/problems/best-time-to-buy-and-sell-stock/

**Describe alternatives you've considered**

**Additional context**

**Comment by dsrao711** [comment]
Please assign me this issue

**Comment by smv1999** [comment]
Sure @dsrao711 , you can go ahead!
