### ISSUE TITLE
Add Insert a Node at the end of a Doubly Linked List

### ISSUE THREAD

**Issue by kiruba-r11** [smv1999/CompetitiveProgrammingQuestionBank#126]
**Is your feature request related to a problem? Please describe.**
I want to add a problem that inserts the node at the end of a Doubly Linked List

**Describe the solution you'd like**
I would like to code this solution in C++

There is a folder named `Linked Lists` inside `Data Structures`. The programs in the `Linked Lists` directory is not properly organized, so I would like to organize them, by creating subdirectories, namely
- Singly Linked Lists
- Doubly Linked Lists
- Circular Linked Lists
- Doubly Circular Linked Lists

and try to add enough programs in each of them, which can be very helpful.

**Comment by kiruba-r11** [comment]
@smv1999 Please assign me this issue.

**Comment by smv1999** [comment]
Sure @kiruba-r11 , you can go ahead !
