### ISSUE TITLE
Python solution for "row with max ones in a matrix " in DSA 450

### ISSUE THREAD

**Issue by dsrao711** [smv1999/CompetitiveProgrammingQuestionBank#128]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

- Link to the problem : https://practice.geeksforgeeks.org/problems/row-with-max-1s0023/

**Describe alternatives you've considered**

**Additional context**

**Comment by dsrao711** [comment]
Please assign me this issue

**Comment by smv1999** [comment]
It is giving 404 not found error when visiting that link. Please check.

**Comment by dsrao711** [comment]
Link for this problem  : https://practice.geeksforgeeks.org/problems/row-with-max-1s0023/1

**Comment by smv1999** [comment]
Cool. You can go ahead @dsrao711 !
