### ISSUE TITLE
Delete a Node from the beginning in Doubly Linked List

### ISSUE THREAD

**Issue by kiruba-r11** [smv1999/CompetitiveProgrammingQuestionBank#137]
**Is your feature request related to a problem? Please describe.**
The problem is to delete a node from the beginning in the Doubly Linked List

**Describe the solution you'd like**
I would like to provide a C++ coded solution to this problem

**Comment by kiruba-r11** [comment]
@smv1999 Please assign this to me

**Comment by smv1999** [comment]
Sure @kiruba-r11 , you can go ahead !
