### ISSUE TITLE
Python solution for 'snake pattern in a matrix ' in DSA 450

### ISSUE THREAD

**Issue by dsrao711** [smv1999/CompetitiveProgrammingQuestionBank#139]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Link for the problem : https://practice.geeksforgeeks.org/problems/print-matrix-in-snake-pattern-1587115621/1

**Describe alternatives you've considered**

**Additional context**

**Comment by dsrao711** [comment]
Please assign me this issue

**Comment by smv1999** [comment]
Sure @dsrao711 , you can go ahead !
