### ISSUE TITLE
Delete a Node from the end in a Doubly Linked Lists

### ISSUE THREAD

**Issue by kiruba-r11** [smv1999/CompetitiveProgrammingQuestionBank#141]
**Is your feature request related to a problem? Please describe.**
The problem is to delete a node from the end in a Doubly Linked List.

**Describe the solution you'd like**
I would like to provide a C++ coded solution to this problem

**Comment by kiruba-r11** [comment]
@smv1999 Please assign it to me.

**Comment by smv1999** [comment]
Sure @kiruba-r11 , you can go ahead !
