### ISSUE TITLE
Add Insert At Head for Circular Linked Lists

### ISSUE THREAD

**Issue by kiruba-r11** [smv1999/CompetitiveProgrammingQuestionBank#145]
**Is your feature request related to a problem? Please describe.**
The problem is to add a node with integer data that is taken as an input from the user and add this node to the head of the Circular Linked List. Circular Linked Lists is a type of Linked Lists that has only the next pointer, but the main difference between SLL and CLL is that CLL's last node's next pointer would point to the head of the CLL

**Describe the solution you'd like**
I would like to create a directory named Circular Linked Lists and provide a C++ coded solution to this problem

**Comment by kiruba-r11** [comment]
@smv1999 I would like to work on this issue.

**Comment by smv1999** [comment]
Sure @kiruba-r11 , you can go ahead !
