### ISSUE TITLE
Delete at Head in a Circular Linked Lists

### ISSUE THREAD

**Issue by kiruba-r11** [smv1999/CompetitiveProgrammingQuestionBank#156]
**Is your feature request related to a problem? Please describe.**
The problem is to delete a node from the head in the Circular Linked Lists.

**Describe the solution you'd like**
I would like to provide a C++ coded solution for this problem.

**Comment by kiruba-r11** [comment]
@smv1999 I would like to work on this.

**Comment by smv1999** [comment]
Sure @kiruba-r11 , you can go ahead !
