### ISSUE TITLE
Add Graph related problems 

### ISSUE THREAD

**Issue by smv1999** [smv1999/CompetitiveProgrammingQuestionBank#16]
Contributors are welcome to add graph related problems !
You are free to choose problem statements from GeeksforGeeks, Hackerrank and LeetCode or any other platforms.

**Comment by pri1311** [comment]
Can I add solutions in c++?

**Comment by smv1999** [comment]
Sure @pri1311 !

**Comment by pri1311** [comment]
I would like to add more solutions. Could you please add the tags crosswoc/ cwoc?

**Comment by smv1999** [comment]
What's that @pri1311 ! This repo is not part of any Winter of Code if that's what you meant. But you can proceed to add more solutions in C++.

**Comment by shahbazalam07** [comment]
I would like to add solutions in java

**Comment by smv1999** [comment]
Sure @shahbazalam07  you can go ahead !

**Comment by shahbazalam07** [comment]
> Sure @shahbazalam07  you can go ahead !

In which folder I have to add ?

**Comment by smv1999** [comment]
You can add them in the graphs folder present [here](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/tree/master/Data%20Structures/Graphs).

**Comment by shahbazalam07** [comment]
OK

**Comment by somya51p** [comment]
@smv1999 I wish to add few graph questions from leetcode. Can I contribute to the same?

**Comment by smv1999** [comment]
Sure @somya51p , you can go ahead !

**Comment by jsourabh1** [comment]
Can I add the graph Algorithms implementation in python ?

**Comment by smv1999** [comment]
Sure @jsourabh1 , But I am afraid this won't be considered towards your contribution to DevIncept 30 days of contribution as the official date for the same is 01 July.I am not sure about. Let us wait for the official guidelines from DevIncept Program Managers Team.

**Comment by vaishnavipatil4848** [comment]
I wish to add graph algorithm implementation in c++. Can I contribute to the same?

**Comment by smv1999** [comment]
Sure @vaishnavipatil4848 , you can go ahead !

**Comment by jsourabh1** [comment]
Now i can add the python algorithms of graph

**Comment by smv1999** [comment]
Sure @jsourabh1 !

**Comment by paurush11** [comment]
I wish to add graph algorithm implementation in c++. Can I contribute to the same @smv1999 ?

**Comment by smv1999** [comment]
Sure @paurush11 , create a separate issue for the specific algorithms that you want to contribute.

**Comment by shraddhamishra611** [comment]
@smv1999 I can provide at least 20+ Graph questions from an interview perspective. Can I contribute?

**Comment by smv1999** [comment]
Sure @shraddhamishra611 , you can go ahead, but create a separate issue for that.
