### ISSUE TITLE
Python solution for Diameter of Binary Tree in DSA 450

### ISSUE THREAD

**Issue by dsrao711** [smv1999/CompetitiveProgrammingQuestionBank#161]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Link to the problem : https://practice.geeksforgeeks.org/problems/height-of-binary-tree/1

**Describe alternatives you've considered**

**Additional context**

**Comment by dsrao711** [comment]
Please assign me this issue

**Comment by smv1999** [comment]
You meant [this](https://practice.geeksforgeeks.org/problems/diameter-of-binary-tree/1) right ?

Sure @dsrao711 , you can go ahead !

**Comment by dsrao711** [comment]
Ya. Sorry for the wrong link

**Comment by smv1999** [comment]
No problem !
