### ISSUE TITLE
Python solution for In order traversal in DSA 450

### ISSUE THREAD

**Issue by dsrao711** [smv1999/CompetitiveProgrammingQuestionBank#163]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Link to the problem : https://leetcode.com/problems/binary-tree-inorder-traversal/submissions/

(Both Recursive and Iterative Solution)

**Describe alternatives you've considered**

**Additional context**

**Comment by smv1999** [comment]
Sure @dsrao711, you can go ahead !
