### ISSUE TITLE
Python solution for Post order traversal in DSA 450

### ISSUE THREAD

**Issue by dsrao711** [smv1999/CompetitiveProgrammingQuestionBank#169]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

(Iterative and recursive solution)
Link for the Problem : https://leetcode.com/problems/binary-tree-postorder-traversal/

**Describe alternatives you've considered**

**Additional context**

**Comment by dsrao711** [comment]
Please assign me this issue

**Comment by smv1999** [comment]
Sure @dsrao711 , you can go ahead !
