### ISSUE TITLE
Python solution for vertical order traversal of a binary tree

### ISSUE THREAD

**Issue by dsrao711** [smv1999/CompetitiveProgrammingQuestionBank#171]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered

Link to the problem : https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/

**Additional context**

**Comment by smv1999** [comment]
Sure @dsrao711 , you can go ahead !
