### ISSUE TITLE
Python solution for deleting a node from BST in DSA 450

### ISSUE THREAD

**Issue by dsrao711** [smv1999/CompetitiveProgrammingQuestionBank#180]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

**Describe the solution you'd like**

**Additional context**

Link to the problem : https://leetcode.com/problems/delete-node-in-a-bst/

**Comment by dsrao711** [comment]
Please assign me this issue

**Comment by smv1999** [comment]
Sure @dsrao711 , you can go ahead !
