### ISSUE TITLE
Python solution for Lowest Common ancestor in DSA 450

### ISSUE THREAD

**Issue by dsrao711** [smv1999/CompetitiveProgrammingQuestionBank#185]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

**Describe the solution you'd like**

Link to the problem : https://practice.geeksforgeeks.org/problems/lowest-common-ancestor-in-a-bst/1

**Additional context**

**Comment by dsrao711** [comment]
Please assign me this issue

**Comment by dsrao711** [comment]
Please assign me this issue

**Comment by smv1999** [comment]
Sure @dsrao711 , you can go ahead !
