### ISSUE TITLE
Python solution for Optimal strategy for game  in DSA 450

### ISSUE THREAD

**Issue by dsrao711** [smv1999/CompetitiveProgrammingQuestionBank#190]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

**Describe the solution you'd like**
Link to the problem : https://practice.geeksforgeeks.org/problems/optimal-strategy-for-a-game-1587115620/1
**Additional context**

**Comment by dsrao711** [comment]
Please assign me this issue

**Comment by smv1999** [comment]
Sure @dsrao711 , you can go ahead !

**Comment by dsrao711** [comment]
Couldnt figure out a proper solution for this. Sorry for the incovenience. Please unassign me this issue
