### ISSUE TITLE
Solutions to be added in Python

### ISSUE THREAD

**Issue by smv1999** [smv1999/CompetitiveProgrammingQuestionBank#2]
Solutions to the programming problems have to added in Python. The current solutions exist in C, C++ and Java.

Developers are welcome to contribute! New problems along with the solutions in Python can also be added.

Happy Coding!

**Comment by 96RadhikaJadhav** [comment]
@smv1999  I wish to work on this!

**Comment by smv1999** [comment]
@96RadhikaJadhav You can start working on this!

**Comment by Ayush7614** [comment]
@smv1999 i am also work on the issue plss assign me

**Comment by smv1999** [comment]
@Ayush7614 You can start working on this.

@96RadhikaJadhav and @Ayush7614 please file a separate issue for the problem that you are going to add in Python so that we can make sure that you both are not working on the same thing.

**Comment by hridaya423** [comment]
I also want to work on Python Problems.
Please assign me @smv1999

**Comment by kiruba-r11** [comment]
@smv1999 Can we work on the existing questions to add solutions in Python?

**Comment by smv1999** [comment]
Sure @kiruba-r11 !

**Comment by lokeshrepaka** [comment]
I to want to work on it

**Comment by smv1999** [comment]
I am closing this issue. For DevIncept, specific issues will be raised rather than generic ones like these. So @lokeshrepaka , you can create a separate issue for a particular problem (or set of problems) for which you want to provide a solution or an alternate solution to the existing problem.
