### ISSUE TITLE
Added problems of Hackerank in Python

### ISSUE THREAD

**Issue by Ayush7614** [smv1999/CompetitiveProgrammingQuestionBank#20]
**Is your feature request related to a problem? Please describe.**
Added problems of Hackerank in Python

**Describe the solution you'd like**
We have to add problems in python related to Hackerank of DSA

**Comment by smv1999** [comment]
Sure @Ayush7614 you can proceed with this. Make sure to add the problems in the appropriate existing categories (folders) and create new folders only if necessary.
