### ISSUE TITLE
Kadane's Algorithm using C++

### ISSUE THREAD

**Issue by RAUNAK-PANDEY** [smv1999/CompetitiveProgrammingQuestionBank#200]
Hey @smv1999 ,
I would like to provide a C++ coded solution for this problem.
Please assign me.
Thanks

**Comment by smv1999** [comment]
Sure @RAUNAK-PANDEY , you may go ahead! But I am afraid this won't be considered towards your contribution to DevIncept 30 days of contribution.

**Comment by RAUNAK-PANDEY** [comment]
Okay ,  thanks for this information.

**Comment by 23-24** [comment]
can I also work on it

**Comment by smv1999** [comment]
If @RAUNAK-PANDEY  isn't working on this issue right now, then you may go ahead @23-24 . But I am afraid this won't be considered towards your contribution to DevIncept 30 days of contribution as the official date for the same is 01 July.

**Comment by RAUNAK-PANDEY** [comment]
@smv1999   Will It be considered if I contribute on this issue after 1 july.

**Comment by smv1999** [comment]
Yes @RAUNAK-PANDEY , I think so.

**Comment by smv1999** [comment]
You can start working on this issue @RAUNAK-PANDEY .

**Comment by RAUNAK-PANDEY** [comment]
Okay thanks.
