### ISSUE TITLE
Adding Trees Section to main project Directory

### ISSUE THREAD

**Issue by i-priyanshu** [smv1999/CompetitiveProgrammingQuestionBank#201]
**Hey @smv1999 ,**
while Going through the main project directory, I didn't found any seprate Trees Section, 
So, I would like to create one for the same.

As the Devincept contributions, are starting from 1st July, i would like to make contribution on that day too.
Is is acceptable?

**Comment by smv1999** [comment]
Trees sub-directory is already present [here](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/tree/master/Data%20Structures). 
Anyway, I guess your contribution will not taken into consideration as it is starting from July.

Utilise the time till 30th June in going through the repo and existing problems and the ways in which they can be optimised or improved. Also, make a list of problems/solutions that you would like to add and keep them ready. Once I receive any official information from the DevIncept team, I would let you know in the slack channel.

**Comment by smv1999** [comment]
I am closing this issue now.

**Comment by i-priyanshu** [comment]
ohh, i didn't see the data structures directory... thanks for your time.
