### ISSUE TITLE
Klee's Algorithm

### ISSUE THREAD

**Issue by neha030** [smv1999/CompetitiveProgrammingQuestionBank#203]
Description: Given a Point with x and y coordinates ,this algorithm finds the union of the
lengths covered by all these line segments.

Sample Input: Enter the desired number of points:
4
Enter the x and y coordinates for the points with a space:
2 4
5 6
3 7
1 6
Sample Output: The union of the length of the line segments is:
6

I want to provide the C++ solution for the above algorithm . 
Please assign me this issue

**Comment by smv1999** [comment]
Sure @neha030 ,you can go ahead. But I am afraid your contributions won't be taken into account as the official period for DevIncept program starts from tomorrow.
