### ISSUE TITLE
Leetcode advanced questions

### ISSUE THREAD

**Issue by sr-sweta** [smv1999/CompetitiveProgrammingQuestionBank#206]
Many interview concept related questions are not yet present in the repo. Many are present in leetcode and interviewbit.

**Comment by smv1999** [comment]
Sure @sr-sweta , you can proceed.

**Comment by Saviour1001** [comment]
Please raise different issues for different questions, address one question in each issue and PR. Raise the issue and we will assign you. Do mention the language you will be contributing it in.

**Comment by sr-sweta** [comment]
Hi Harsh can I still fork and do raise a pr as the mail of issue closed
came. And now its the active time when actual program is going on.

**Comment by Saviour1001** [comment]
@sr-sweta Raise a new issue, state the question in that issue, the language you will be using and then start working on it. One question per issue is a must.

**Comment by sr-sweta** [comment]
Thank you for the clarification. I will definitely do that.
