### ISSUE TITLE
Dining Philosopher's Problem

### ISSUE THREAD

**Issue by khushboo2202** [smv1999/CompetitiveProgrammingQuestionBank#207]
i want to work on this problem in c++
plzz assign me this issue

**Comment by smv1999** [comment]
Sure @khushboo2202 , you can go ahead !

**Comment by ritikaranj** [comment]
I want to work in this . Please assign me.

**Comment by smv1999** [comment]
@ritikaranj which language you want to contribute this problem in ?

**Comment by ritikaranj** [comment]
Cpp.

**Comment by smv1999** [comment]
@khushboo2202 has already started working on this issue in C++. You will need to go for another language as the issues are assigned on FCFS basis.
