### ISSUE TITLE
Solutions to problems in java and python

### ISSUE THREAD

**Issue by dilroseR** [smv1999/CompetitiveProgrammingQuestionBank#210]
Convert roman to its equivalent integer- Python
To find sum of K Largest pairs- Python
Remove palindromic subsequences - Java
Shortest Unsorted Continuous Subarray -Python

I want to add these new programs into the repo

**Comment by PranavKapoor28** [comment]
> Convert roman to its equivalent integer- Python
> To find sum of K Largest pairs- Python
> Remove palindromic subsequences - Java
> Shortest Unsorted Continuous Subarray -Python
> 
> I want to add these new programs into the repo

In which repo, should I add

**Comment by dilroseR** [comment]
actually, I want to contribute all these.. I'm waiting for admins to assign it to me

**Comment by dilroseR** [comment]
> > Convert roman to its equivalent integer- Python
> > To find sum of K Largest pairs- Python
> > Remove palindromic subsequences - Java
> > Shortest Unsorted Continuous Subarray -Python
> > I want to add these new programs into the repo
> 
> In which directory , should I add

**Comment by smv1999** [comment]
Sure @dilroseR , you can go ahead !

**Comment by dilroseR** [comment]
> Sure @dilroseR , you can go ahead !

thankyou
