### ISSUE TITLE
Interview Questions

### ISSUE THREAD

**Issue by saimanvitha02** [smv1999/CompetitiveProgrammingQuestionBank#214]
Hey, I came across this repo when I was seeing to contribute for DCP 2021. I would like to add few questions that I solved on LeetCode since the past few days. Can I do that here? Also, there are few interview questions that I would like to add but I do not know the solution to them. Can we add such kind of questions as well? If yes, please let me do this.

**Comment by smv1999** [comment]
Yes @saimanvitha02 , you can add the leetcode solutions. And the questions for which you don't know the solutions, create the issues for the same so others who might know the solutions can contribute to the same.

**Comment by sujay2306** [comment]
can yu assign me to this issue

**Comment by saimanvitha02** [comment]
Hi @sujay2306, I'm already working on this issue. I was waiting till 10th to start making pull requests as mentioned in the group.

**Comment by shraddhamishra611** [comment]
@smv1999, I can add Array and String questions mostly asked in the Interview, assign me this issue.

**Comment by smv1999** [comment]
@shraddhamishra611, please create a separate issue for the same.

**Comment by Saviour1001** [comment]
@saimanvitha02 solve only one question in a single issue. If you want to add multiple problems make separate issues for each one of them. And also mention the language you will be using.

**Comment by smv1999** [comment]
@saimanvitha02, Please mention the language so that we can appropriate labels.

**Comment by Saviour1001** [comment]
@saimanvitha02 as you are inactive we are closing this issue. If you still want to contribute, raise a new issue and make sure to add only one specific question per PR/issue.
