### ISSUE TITLE
Rabin-Karp Algorithm and KMP Algorithm

### ISSUE THREAD

**Issue by dhanashreeg368** [smv1999/CompetitiveProgrammingQuestionBank#225]
I want to add Rabin-Karp Algorithm and KMP algorithm (for pattern searching in a String) in Strings Folder. Please assign me this issue..

**Comment by smv1999** [comment]
Sure @dhanashreeg368 , you can go ahead !

**Comment by harshita9621** [comment]
Can I work on this issue?

**Comment by dhanashreeg368** [comment]
I am already working on it.

**Comment by smv1999** [comment]
Which language are you contributing in @dhanashreeg368 ?

**Comment by harshita9621** [comment]
@smv1999 Can I work in C++.

**Comment by dhanashreeg368** [comment]
I am contributing in C++ language.

**Comment by Saviour1001** [comment]
@harshita9621 you can work on the same problem in some different language, please raise a different issue for that.
