### ISSUE TITLE
Center of Star Graph

### ISSUE THREAD

**Issue by neha030** [smv1999/CompetitiveProgrammingQuestionBank#226]
A star graph is an undirected graph that has n nodes in which one is center node and has exactly n - 1 edges.

                  4
                  |
                  2
                 / \
               1   3 
Here 2 is the answer.

I want to provide C++ code for the above program .
Please assign me this issue.

**Comment by smv1999** [comment]
Sure @neha030, you can go ahead ! Make sure to add a detailed description of the problem statement at the top of the file that you submit for PR.
