### ISSUE TITLE
Python solution for Max sum problem in DSA 450

### ISSUE THREAD

**Issue by dsrao711** [smv1999/CompetitiveProgrammingQuestionBank#227]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

**Describe the solution you'd like**

**Additional context**

link to the problem : 
https://practice.geeksforgeeks.org/problems/maximum-sum-problem2211/1

**Comment by dsrao711** [comment]
Please assign me this issue

**Comment by smv1999** [comment]
Sure @dsrao711, you can go ahead !
