### ISSUE TITLE
Python solution for climbing stairs - Dynamic Programming

### ISSUE THREAD

**Issue by dsrao711** [smv1999/CompetitiveProgrammingQuestionBank#233]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

**Describe the solution you'd like**

**Additional context**

Link to the problem : https://leetcode.com/problems/climbing-stairs/

**Comment by dsrao711** [comment]
Please assign me this issue

**Comment by smv1999** [comment]
Sure @dsrao711, you can go ahead !
