### ISSUE TITLE
Detect Cycle In Linked List

### ISSUE THREAD

**Issue by neha030** [smv1999/CompetitiveProgrammingQuestionBank#235]
A Linked List is a linear data structure which includes a series of connected nodes. Each node stores the data and the address of the next node.
    If any node is visited more than once while traversing the list then we can say that it contains cycle/loop.
     Example:

             1 -> 2 -> 3
                    ^      |
                    |       v
                    5 <-  4   
                                
     Output : True

I want to add the C++ code for this in Data Structure->Linked List folder
Please assign me this issue

**Comment by neha030** [comment]
![Screenshot (198)](https://user-images.githubusercontent.com/72595335/124390786-b752cb00-dd0a-11eb-9d9b-52424f7ed3be.png)

**Comment by smv1999** [comment]
Sure @neha030, you can go ahead !

**Comment by priyanshi5** [comment]
@smv1999 Please assign this issue to me , I would like to solve this in Python.

**Comment by inimitable034** [comment]
I would like to sove this too.
Please assign the issue to me

**Comment by smv1999** [comment]
Sure @priyanshi5, you can go ahead !

**Comment by smv1999** [comment]
Which language do you want to solve this in ?

**Comment by inimitable034** [comment]
> @inimitable034 Which language do you want to solve this in ?

i can solve in java and javascript both

**Comment by smv1999** [comment]
Sure @inimitable034, you can go ahead then.
