### ISSUE TITLE
Subset problems using backtracking

### ISSUE THREAD

**Issue by akugarg** [smv1999/CompetitiveProgrammingQuestionBank#239]
There are several problems related to subsets and combination sums. I want to add those problems in backtracking topics which are not currently in the repo. I would be using C++ for writing the solution.

**Comment by smv1999** [comment]
Sure @akugarg, you can go ahead !

**Comment by Saviour1001** [comment]
@akugarg please make sure to use one issue for one problem and one PR per problem, and also mention the language you will be using.
