### ISSUE TITLE
Kadene's Algorithm

### ISSUE THREAD

**Issue by inimitable034** [smv1999/CompetitiveProgrammingQuestionBank#240]
This would contain the most efficient subarray operation for sum and etc..

**Comment by smv1999** [comment]
@inimitable034 , kadane's algorithm is already present in C and C++. 
Always mention the language in which you want to solve this in the issue description.

**Comment by inimitable034** [comment]
Okayy 
i will keep that in mind .
I would like to solve in java

**Comment by smv1999** [comment]
Okay cool, you can go ahead !

**Comment by KeerthanaPravallika** [comment]
Can I solve kadane's algorithm in python. Can you please assign me

**Comment by shraddhamishra611** [comment]
@smv1999, I can solve this problem in Java with Time Complexity: O(N)

**Comment by smv1999** [comment]
@KeerthanaPravallika please create a new issue.

**Comment by smv1999** [comment]
@inimitable034, are you still working on it ?

**Comment by Saviour1001** [comment]
@inimitable034 please use one PR for each language, others are free to open the issues in different languages which are not present their

**Comment by inimitable034** [comment]
> @inimitable034, are you still working on it ?

yes sir
