### ISSUE TITLE
Topological Sort

### ISSUE THREAD

**Issue by neha030** [smv1999/CompetitiveProgrammingQuestionBank#244]
Topological sorting for Directed Acyclic Graph (DAG) is a linear ordering
  of vertices such that for every directed edge uv, vertex u comes before v in
  the ordering. Topological Sorting for a graph is not possible if the graph is
  not a DAG.

Input:
Enter number of node you want to add: 6
Enter nodes of graph: 
5 2 
5 0 
4 0 
4 1 
2 3 
3 1 
Output:
Graph after topological sort: 
5 4 2 3 1 0 

I want to add the C++ code for this in Sorting Algorithm Folder
Please assign me this issue

**Comment by smv1999** [comment]
Sure @neha030, you can go ahead! Place the code in Data Structures/Graphs/ folder.
