### ISSUE TITLE
Bucket sort

### ISSUE THREAD

**Issue by neha030** [smv1999/CompetitiveProgrammingQuestionBank#245]
Bucket sort is a sorting algorithm that works by distributing the elements of an array into a number of buckets.
Each bucket is then sorted individually, either using a different sorting algorithm,
or by recursively applying the bucket sorting algorithm. Bucket sort is mainly useful when input is uniformly distributed
over a range. Bucket sort can be implemented with comparisons and therefore can also be considered a comparison sort algorithm.

Input:
Enter the number of elements :
4
Enter the elements:
0.123 0.008 0.7 0.4
Output:
Sorted array is
0.008 0.123 0.4 0.7

I want to add the C++ code for this in Sorting Algorithm Folder
Please assign me this issue

**Comment by smv1999** [comment]
Sure @neha030, you can go ahead !

**Comment by priyanshi5** [comment]
@smv1999 Please assign this issue to me, I would like to solve this in Python.

**Comment by smv1999** [comment]
Sure @priyanshi5, you can go ahead !
