### ISSUE TITLE
Python solution  for Mirror of Binary Tree in DSA 450

### ISSUE THREAD

**Issue by dsrao711** [smv1999/CompetitiveProgrammingQuestionBank#246]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

**Describe the solution you'd like**

**Additional context**
Link to the problem : https://practice.geeksforgeeks.org/problems/mirror-tree/1/

**Comment by smv1999** [comment]
Sure @dsrao711, you can go ahead !
