### ISSUE TITLE
 Combinatorics

### ISSUE THREAD

**Issue by SanthoshPatkar** [smv1999/CompetitiveProgrammingQuestionBank#247]
I want to add some combinatorics-related problems. Please assign this issue

**Comment by smv1999** [comment]
Sure @SanthoshPatkar, you can go ahead !

**Comment by Saviour1001** [comment]
@SanthoshPatkar make sure to add only one question in each issue , make multiple issues for multiple questions.

**Comment by smv1999** [comment]
@SanthoshPatkar , Also mention the language.

**Comment by SanthoshPatkar** [comment]
okay sure
