### ISSUE TITLE
Add more problems in General Questions

### ISSUE THREAD

**Issue by nileshkr9919** [smv1999/CompetitiveProgrammingQuestionBank#250]
Adding solutions of some pattern printing problems asked in ### _**INTERVIEWS**_.

Like:

1) 
 ![WhatsApp Image 2021-07-06 at 1 33 00 PM](https://user-images.githubusercontent.com/68392556/124564776-06117980-de5f-11eb-80f3-6f05239623f2.jpeg)

2) 
![WhatsApp Image 2021-07-06 at 1 36 39 PM (1)](https://user-images.githubusercontent.com/68392556/124565169-5d174e80-de5f-11eb-810d-0558414d3252.jpeg)

3)
123
12345
1234567
123456789

I request you to assign it to me.

**Comment by smv1999** [comment]
Sure @nileshkr9919, but please mention in which language you want to submit the solution in ?

**Comment by nileshkr9919** [comment]
I think it will be better in C, as will be easier for beginners to understand.

**Comment by smv1999** [comment]
You can go ahead !

**Comment by Shimpirawat** [comment]
Hello, I would like to add some star pattern questions in C.

**Comment by smv1999** [comment]
Some pattern based problems are already present [here](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/tree/master/General%20Questions). You can have a look at them. 
If you want to contribute, you can create a new issue stating the problem that you want to solve.

**Comment by ritikaranj** [comment]
Implement Merge Sort i.e. standard implementation keeping the sorting algorithm as in-place. 

May, I go ahead with this in CPP??

**Comment by smv1999** [comment]
Sure @ritikaranj, you can go ahead. Make sure to place the problem under Sorting Algorithms folder.

**Comment by ritikaranj** [comment]
Ok , Thank you.

**Comment by ritikaranj** [comment]
I have a doubt about this program.
When should we have to add code, after getting groups assigned or now?

**Comment by smv1999** [comment]
The contribution period starts officially on 10th July. If you require more information regarding the program, please contact the Program Managers in Slack.

**Comment by ritikaranj** [comment]
Okk , Thank you
