### ISSUE TITLE
Update on readme.md 

### ISSUE THREAD

**Issue by PrathmeshMutke** [smv1999/CompetitiveProgrammingQuestionBank#253]
**Is your feature request related to a problem? Please describe.**
Addition of extra features to readme.md file for best view

**Comment by PrathmeshMutke** [comment]
Please assign me this issue
Devincept

**Comment by smv1999** [comment]
What changes are you exactly trying to make ? Be as descriptive as possible.

**Comment by PrathmeshMutke** [comment]
I want to add mit licence gif

**Comment by smv1999** [comment]
Okay, you can go ahead !
