### ISSUE TITLE
Python solution for rotate matrix by 90 degree in anticlockwise direction 

### ISSUE THREAD

**Issue by dsrao711** [smv1999/CompetitiveProgrammingQuestionBank#261]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

**Describe the solution you'd like**

**Additional context**
Link to the problem : 
https://practice.geeksforgeeks.org/problems/rotate-by-90-degree0356/1/

**Comment by dsrao711** [comment]
Please assign me this issue

**Comment by smv1999** [comment]
Sure @dsrao711, you can ahead !
