### ISSUE TITLE
Longest Common Substring in cpp

### ISSUE THREAD

**Issue by KeerthanaPravallika** [smv1999/CompetitiveProgrammingQuestionBank#262]
I want to work on this issue. Can you please assign me with this issue (DevIncept contribution)

**Comment by shindesuyog** [comment]
I would like to work on this problem. you can assign me this.

**Comment by ritikaranj** [comment]
I want to work on this problem . Please assign me

**Comment by smv1999** [comment]
@KeerthanaPravallika @shindesuyog @ritikaranj please mention the language in which you want to contribute ?

**Comment by ritikaranj** [comment]
I want to contribute in cpp

**Comment by KeerthanaPravallika** [comment]
> @KeerthanaPravallika @shindesuyog @ritikaranj please mention the language in which you want to contribute ?

I want to contribute in CPP as mentioned in the issue

**Comment by smv1999** [comment]
Sure @KeerthanaPravallika, you can go ahead !

**Comment by smv1999** [comment]
You will need to choose any other language @ritikaranj .

**Comment by shindesuyog** [comment]
I will do it in cpp

**Comment by smv1999** [comment]
You will need to choose any other language @shindesuyog

**Comment by harshita9621** [comment]
Can I work on this issue using C.

**Comment by smv1999** [comment]
Yes, sure @harshita9621 .
