### ISSUE TITLE
Generate Multiplication table of a given Number in C.

### ISSUE THREAD

**Issue by Shimpirawat** [smv1999/CompetitiveProgrammingQuestionBank#263]
I would like to work on this issue. please assign it to me.

**Comment by smv1999** [comment]
Although it can be added in Basic Programs in Numbers folder, please try to bring in problems that are considered from an interview point of view. Explore platforms such as HackerRank, LeetCode and Geeks for Geeks. Would you like to go ahead with this issue ?

**Comment by ritikaranj** [comment]
Can I go ahead with this problem?

**Comment by smv1999** [comment]
Refer to issue #265

**Comment by ritikaranj** [comment]
okkk
