### ISSUE TITLE
Important Announcement

### ISSUE THREAD

**Issue by smv1999** [smv1999/CompetitiveProgrammingQuestionBank#265]
Make sure to add problems that are considered important from an interview point of view and those that will help the candidates to get a deeper understanding of DSA concepts.

**Comment by Soham2020** [comment]
Hi....
Can I add some problems on binary search ?
Problems:
1. First and last occurrence of an element in a sorted array.
2.  Count the frequency of an element in a sorted array.
3. Number of times a sorted array is rotated.
4. Find the element in an rotated sorted array.
