### ISSUE TITLE
Backtracking Questions

### ISSUE THREAD

**Issue by bhagyashree-06** [smv1999/CompetitiveProgrammingQuestionBank#268]
I want to add few Backtracking problems ( Combinational Sum, Subset sum problem, Permutations of a String etc. ) in Python3

Can you assign me this issue ?

**Comment by smv1999** [comment]
Sure @bhagyashree-06, you can go ahead !

**Comment by bhagyashree-06** [comment]
> Sure @bhagyashree-06, you can go ahead !

Okay !

**Comment by harshita9621** [comment]
@smv1999 Can I work on this issue using language C++.

**Comment by smv1999** [comment]
Sure @harshita9621, you can go ahead !
