### ISSUE TITLE
Python solution for Subtree of another tree

### ISSUE THREAD

**Issue by dsrao711** [smv1999/CompetitiveProgrammingQuestionBank#269]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

**Describe the solution you'd like**

**Additional context**

Link for the problem : https://leetcode.com/problems/subtree-of-another-tree/

**Comment by dsrao711** [comment]
Please assign me this issue

**Comment by smv1999** [comment]
The link that you have mentioned is not of "Check if BST"

**Comment by dsrao711** [comment]
https://practice.geeksforgeeks.org/problems/check-if-subtree/1/ 
and https://leetcode.com/problems/subtree-of -another-tree/  but are same problems . Changed the title

**Comment by smv1999** [comment]
> https://practice.geeksforgeeks.org/problems/check-if-subtree/1/
> and
> https://leetcode.com/problems/subtree-of-another-tree/
> but are same problems . Changed the title

Yeah, that's okay. But previous the title was "Check if BST".

Anyway, you can go ahead !
