### ISSUE TITLE
Maximum Subarray Sum in C++

### ISSUE THREAD

**Issue by ishikasinha-d** [smv1999/CompetitiveProgrammingQuestionBank#272]
Problem Statement: Find the maximum sum of values in a contiguous, nonempty subarray from an array of size n.

Contributor Type: Devincept 

Please assign me this question. Will solve in C++.

**Comment by harshita9621** [comment]
@smv1999 Can I work on this issue

**Comment by smv1999** [comment]
@ishikasinha-d and @harshita9621  , the problem already exists [here](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/tree/master/Arrays) in C++ and C.You can contribute in any other language.

**Comment by ishikasinha-d** [comment]
@smv1999 Can I contribute in python?

**Comment by Anupam-Panwar** [comment]
I would like to the solution of this question in java

**Comment by shubhdholakiya** [comment]
Hello, @smv1999 Can I contribute here with Java and Python?

**Comment by Saviour1001** [comment]
@ishikasinha-d @Anupam-Panwar @shubhdholakiya please raise a different issue for implementing Kadane's Algorithm in Java and Python. The issue will be assigned to the person on the basis of first come first serve.
