### ISSUE TITLE
Bubble sort in python

### ISSUE THREAD

**Issue by siddhi-244** [smv1999/CompetitiveProgrammingQuestionBank#273]
**Describe the solution you'd like**
I would like to add Bubble sort in python.

**Additional context**

**Comment by siddhi-244** [comment]
Please assign this to me under devincept!

**Comment by smv1999** [comment]
Sure @siddhi-244, you can go ahead !

**Comment by siddhi-244** [comment]
@smv1999  you haven't added labels!
