### ISSUE TITLE
Sum of three values 

### ISSUE THREAD

**Issue by ishikasinha-d** [smv1999/CompetitiveProgrammingQuestionBank#274]
Problem Statement: Given an array of size n. The task is to find three values (at distinct positions) whose sum is x. (1<=n<=5000, 1<=x<=10^9)                               

Contributor Type: Devincept

Solution:
I will use the concept of pointers and sorting. 

Please assign me this question. Will solve in C++.

**Comment by harshita9621** [comment]
Please assign me this question. Will solve in C.

**Comment by smv1999** [comment]
Sure @ishikasinha-d, you can go ahead !

**Comment by smv1999** [comment]
Sure @harshita9621, you can also go ahead !
