### ISSUE TITLE
GCD SUMs

### ISSUE THREAD

**Issue by vanishasamriddhi** [smv1999/CompetitiveProgrammingQuestionBank#275]
**Is your feature request related to a problem? Please describe.**
I want to give solution to problem: https://www.codechef.com/problems/SUMGCD
**Describe the solution you'd like**
I want to give the solution in C++.

I'm a contributor from DevIncept.

**Comment by smv1999** [comment]
Sure @vanishasamriddhi, you can go ahead !

**Comment by vanishasamriddhi** [comment]
Hey @smv1999  This problem is a medium- hard type question. So, If possible do change the tag.
