### ISSUE TITLE
Hill Sequence

### ISSUE THREAD

**Issue by vanishasamriddhi** [smv1999/CompetitiveProgrammingQuestionBank#276]
**Is your feature request related to a problem? Please describe.**
I want to give the solution of problem: https://www.codechef.com/problems/HILLARR
**Describe the solution you'd like**
I want to give the solution in C++.

**Additional context**
I'm a contributor from DevIncept.

**Comment by smv1999** [comment]
Sure @vanishasamriddhi, you can go ahead !

**Comment by vanishasamriddhi** [comment]
Hey, @smv1999 This problem is a medium question, If possible do change the tag.
