### ISSUE TITLE
Trapping rain water

### ISSUE THREAD

**Issue by vishvarana** [smv1999/CompetitiveProgrammingQuestionBank#278]
Problem statement :
https://leetcode.com/problems/trapping-rain-water/description/

I will provide the code in c++ language

**Comment by Anupam-Panwar** [comment]
I would like to add this question in java

**Comment by smv1999** [comment]
Sure @vishvarana, you can go ahead !

**Comment by smv1999** [comment]
@Anupam-Panwar, please create a new issue for that.

**Comment by vishvarana** [comment]
I have made a pull request regarding this issue.
Please review
#567
