### ISSUE TITLE
Add Sieve of Eratosthenes

### ISSUE THREAD

**Issue by ushmita4** [smv1999/CompetitiveProgrammingQuestionBank#279]
I wish to add Sieve of Eratosthenes to the repository. It will be in the C language.

**Comment by ishikasinha-d** [comment]
Can I add this algorithm in C++?

**Comment by harshita9621** [comment]
Can I work on this by using C++.

**Comment by smv1999** [comment]
@ushmita4, always mention the language in which you want to contribute.

**Comment by ushmita4** [comment]
> @ushmita4, always mention the language in which you want to contribute.

Ok, Sir. Sir, I wish to contribute to it in C language.

**Comment by Saviour1001** [comment]
@ushmita4 you could go ahead and contribute, @harshita9621 @ishikasinha-d, you guys could raise a new issue for contributing in C++ and adding Sieve and I will assign you that
