### ISSUE TITLE
Check whether Kth bit is set or not

### ISSUE THREAD

**Issue by ishikasinha-d** [smv1999/CompetitiveProgrammingQuestionBank#282]
Problem: Given a number N and a bit number K, check if the Kth bit of N is set or not. Position of set bit '1' should be indexed starting with 0 from the LSB side in the binary representation of the number.

Example 
Input: N = 4, K = 0
Output: No

Please assign me this problem as DevIncept Contributor. I will solve in C++

**Comment by ishikasinha-d** [comment]
Also this question was asked in Microsoft

**Comment by smv1999** [comment]
Sure @ishikasinha-d, you can go ahead
