### ISSUE TITLE
Maximum subset XOR

### ISSUE THREAD

**Issue by ishikasinha-d** [smv1999/CompetitiveProgrammingQuestionBank#284]
Problem: Given an array of N positive integers. Find an integer denoting the maximum XOR subset value in the given array.
Asked in Microsoft
Concept: Bit manipulation

Contributor: DevIncept

Please assign this to me. Will solve in C++

**Comment by shubhdholakiya** [comment]
Hello, I can solve this in CPP and Even I can work with Python. Can I contribute over here?

**Comment by smv1999** [comment]
Sure @ishikasinha-d, you can go ahead !

**Comment by smv1999** [comment]
@shubhdholakiya, please create a new issue, if you want to solve this in Python.

**Comment by ishikasinha-d** [comment]
@smv1999 Should I put it in the bit manipulation folder? Or create another folder for questions asked in  Interview?

**Comment by smv1999** [comment]
Yes put it in Bit Manipulation folder @ishikasinha-d
