### ISSUE TITLE
Remove all Duplicates from Linkedlist

### ISSUE THREAD

**Issue by neha030** [smv1999/CompetitiveProgrammingQuestionBank#287]
Given the Sorted Linked list head which contain duplicates, the task is
to delete all the duplicate and make linked list such that every element
appear just one time.
Example:
Original Linked list : 1 1 2 2 3
Answer : 1 2 3

I want to add the C++ code for this in data structure->Linkedlist folder
Please assign me this issue under DCP'21.

**Comment by shraddhamishra611** [comment]
I can provide solutions in Python. Please assign me this issue.

**Comment by smv1999** [comment]
Sure @neha030, you can go ahead !
