### ISSUE TITLE
Palindrome doubly linked list

### ISSUE THREAD

**Issue by neha030** [smv1999/CompetitiveProgrammingQuestionBank#288]
DOUBLY LINKED LIST TO CHECK IF A STRING IS PALINDROME
A string is accepted as input from the user. The characters in the string are inserted as nodes into the doubly linked list.
Two pointers lptr and rptr are used to point to the beginning and end of the string respectively. The list is traversed from left to right using lptr and right to left using rptr. If the characters match until they reach the same node the string is palindrome

I want to add the C++ code for this in data structure->Linkedlist folder
Please assign me this issue under DCP'21

**Comment by shraddhamishra611** [comment]
@smv1999 One way is to clone and then reverse the list and then compare but it will take extra space. Optimize solution is using recursion. 
I want to add the Java code for this problem statement.
Please assign me this issue.

**Comment by shubhdholakiya** [comment]
Hello @smv1999, Can I contribute to this, please? I can do this with CPP and Python.

**Comment by smv1999** [comment]
Sure @neha030, you can go ahead !

**Comment by smv1999** [comment]
@shubhdholakiya @shraddhamishra611 please create new issues for the same.
