### ISSUE TITLE
Minimize the maximum difference between heights

### ISSUE THREAD

**Issue by shraddhamishra611** [smv1999/CompetitiveProgrammingQuestionBank#289]
Given an array denoting heights of N towers and a positive integer K, you have to modify the height of each tower either by increasing or decreasing them by K only once. After modifying, height should be a non-negative integer. 

Find out what could be the possible minimum difference of the height of shortest and longest towers after you have modified each tower.
K = 3, N = 5
Arr[] = {3, 9, 12, 16, 20}
Output:
11

I want to add the C++ code for this in the data structure->Arrays folder
Please assign me this issue.

**Comment by smv1999** [comment]
Sure @shraddhamishra611, you can go ahead !
