### ISSUE TITLE
Balanced Parenthesis Problem

### ISSUE THREAD

**Issue by shraddhamishra611** [smv1999/CompetitiveProgrammingQuestionBank#290]
Given an expression string x. Examine whether the pairs and the orders of “{“,”}”,”(“,”)”,”[“,”]” are correct in exp.

For example, the function should return 'true' for exp = “{([])}” and 'false' for exp = “[ ( ] )”.

I want to add the Java code for this in the data structure->Strings folder
Please assign me this issue.

**Comment by suprithars111** [comment]
@smv1999  Can you please assign me this issue in C++

**Comment by smv1999** [comment]
Sure @shraddhamishra611, you can go ahead. But place the problem in Data Structures -> Stack folder.

**Comment by smv1999** [comment]
@suprithars111, the solution is already available in C++. You can solve it any other language. Would you like to go ahead ?

**Comment by shraddhamishra611** [comment]
> Sure @shraddhamishra611, you can go ahead. But place the problem in Data Structures -> Stack folder.

**Comment by shraddhamishra611** [comment]
> Sure @shraddhamishra611, you can go ahead. But place the problem in Data Structures -> Stack folder.

**Comment by shraddhamishra611** [comment]
> Sure @shraddhamishra611, you can go ahead. But place the problem in Data Structures -> Stack folder.

Okay, I'll place it under Stack folder
