### ISSUE TITLE
Implement Trie data structure

### ISSUE THREAD

**Issue by bhavik-m** [smv1999/CompetitiveProgrammingQuestionBank#291]
Implement a Trie data structure in C++

I believe this is a really important question if we look after Interview perspective. 

This question is asked in Google , Amazon , Microsoft, Uber, Flipkart

I want to add the c++ code for this.
Please assign me this issue.

**Comment by harshita9621** [comment]
Can I also work on this issue

**Comment by shraddhamishra611** [comment]
@smv1999 Please assign me this issue

**Comment by smv1999** [comment]
Sure @bhavik-m, you can go ahead !

**Comment by smv1999** [comment]
@harshita9621 and @shraddhamishra611 please specify the language.

**Comment by harshita9621** [comment]
In C++

**Comment by Saviour1001** [comment]
@harshita9621 @shraddhamishra611  you guys could find some other problem that doesn't already exist in the repo and raise an issue. Please raise your own issue and you will be assigned.

**Comment by shraddhamishra611** [comment]
> @harshita9621 @shraddhamishra611 you guys could find some other problem that doesn't already exist in the repo and raise an issue. Please raise your own issue and you will be assigned.

Okay, I'll raise my own issue. @Saviour1001
