### ISSUE TITLE
Water Jug Problem

### ISSUE THREAD

**Issue by Manasi2001** [smv1999/CompetitiveProgrammingQuestionBank#292]
**Is your feature request related to a problem? Please describe.**
Given Problem: You are given a 'm' liter jug and a 'n' liter jug where 
'0<m<n'. Both the jugs are initially empty. The jugs don't have markings 
to allow measuring smaller quantities. You have to use the jugs to measure 
'd' liters of water where 'd<n'. Determine the minimum no of operations to 
be performed to obtain 'd' liters of water in one of jug.

**Describe the solution you'd like**
The aim is to solve this problem using BFS or DFS as per user's choice.

**Comment by harshita9621** [comment]
Can I work on this issue using C++.

**Comment by smv1999** [comment]
Sure @Manasi2001 you can go ahead. Please mention the language in which you want to contribute.

**Comment by smv1999** [comment]
@harshita9621, please create a separate issue .

**Comment by Manasi2001** [comment]
> Sure @Manasi2001 you can go ahead. Please mention the language in which you want to contribute.

Python
