### ISSUE TITLE
Graph Coloring Problem

### ISSUE THREAD

**Issue by Karnika06** [smv1999/CompetitiveProgrammingQuestionBank#293]
# Aim

To determine all the different ways in which graph can be colored using at most _m_ colors.

# Details

- Graph represented by its adjacency matrix.
- Colors are represented by the integers 1,2,...,m.
- I will be using Backtracking to solve this problem.

I wish to work on this issue in C++ language.
Please assign this issue to me.

**Comment by smv1999** [comment]
Sure @Karnika06, you can go ahead !
