### ISSUE TITLE
Find all possible Permutations of a String

### ISSUE THREAD

**Issue by Karnika06** [smv1999/CompetitiveProgrammingQuestionBank#294]
# Aim

In this problem all the possible permutations of a input string will be printed as output.

# Details

- **Algorithm Paradigm** - I will be using Backtracking for this problem.

I wish to work on this problem in JAVA language.
Please assign this to me.

**Comment by smv1999** [comment]
Sure @Karnika06, you can go ahead !

**Comment by sravanyabendi** [comment]
Please assign me to this issue

**Comment by smv1999** [comment]
If you want to work on the same problem but in a different language, please create a new issue for that.
