### ISSUE TITLE
Responsive Design for mobile and Accessibility

### ISSUE THREAD

**Issue by william-monroy** [smv1999/CompetitiveProgrammingQuestionBank#295]
### Description
The web page does not display correctly on phones because there is a large white margin on the right side. Also in terms of accessibility, the images do not have alternative labels in case they could not be loaded. Could you assign me this issue?

### Screenshot
![phone_screenshot](https://user-images.githubusercontent.com/58092741/125179815-b365f380-e1b7-11eb-9acd-d8027c1f1ad4.jpeg)

**Desktop (please complete the following information):**
 - OS: Android
 - Version 11

**Comment by smv1999** [comment]
@william-monroy , The website was created using github pages and existing template.

**Comment by smv1999** [comment]
I am closing this issue since it is a template and can't be modified.
