### ISSUE TITLE
Count Union of two arrays

### ISSUE THREAD

**Issue by shraddhamishra611** [smv1999/CompetitiveProgrammingQuestionBank#298]
Union of the two arrays can be defined as the set containing distinct elements from both the arrays. 
If there are repetitions, then only one occurrence of element should be considered in the union. 
The final count should be printed.

Input:
85 25 1 32 54 6
85 2 
Output: 
7

I want to add the C++ code using sets for this in the DSA 450 folder
Please assign me this issue @smv1999

**Comment by smv1999** [comment]
Sure @shraddhamishra611, you can go ahead !
