### ISSUE TITLE
Programmers are Welcome to Contribute 

### ISSUE THREAD

**Issue by smv1999** [smv1999/CompetitiveProgrammingQuestionBank#3]
Developers are highly welcome to contribute to this project by modifying the existing solutions to more optimized solutions or add new programs that fit into the various categories mentioned in the repo or adding a new category if needed.

Please refer [this](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md) for more info.

**Comment by nikita-jain-01** [comment]
Hey!
I would like to work on this. Please assign it to me.

**Comment by smv1999** [comment]
Sure @nikita-jain-01 !

**Comment by hridaya423** [comment]
Hey,
I would like to work on this! Please assign it to me.

**Comment by smv1999** [comment]
Sure @hridaya423 !

**Comment by hridaya423** [comment]
Could I add python programs?

**Comment by lokeshrepaka** [comment]
I to want to contribute to it. Please join me also.

**Comment by Swayam933** [comment]
Hey @smv1999 I would like to contribute Books, materials and technical blogs of all tech stacks and more. So, can i ?

**Comment by divyaachoudharyy** [comment]
Hey! I would like to work on this.

**Comment by smv1999** [comment]
Sure @Swayam933 , create a separate issue stating how you are going to do that. Are you going to share links of the materials or the materials themselves ?

**Comment by smv1999** [comment]
Sure @divyaachoudharyy , you can create a separate issue stating the problems that you want to add.
