### ISSUE TITLE
Binary Search in cpp

### ISSUE THREAD

**Issue by siddhi-244** [smv1999/CompetitiveProgrammingQuestionBank#303]
**Is your feature request related to a problem? Please describe.**
To add Binary Search in cpp

**Describe the solution you'd like**
I would like to add binary search in cpp language 

**Additional context**

**Comment by siddhi-244** [comment]
Plz assign this to me under DCP'21

**Comment by smv1999** [comment]
Sure @siddhi-244, you can go ahead !
