### ISSUE TITLE
OOPS : ALL TYPES OF INHERITANCE CODES

### ISSUE THREAD

**Issue by pushpakumari5117** [smv1999/CompetitiveProgrammingQuestionBank#305]
**@smv1999 
PLEASE GO THROUGH THIS IDEA ONCE AND ASSIGN IT TO ME UNDER THE DCP21 LABEL, IT WILL BE A GREAT CONTRIBUTION TO YOUR OOPS FOLDER.** 

**DESCRIPTION :** 

I want to add code for all 5 types of inheritances in C++.
- Single Inheritance
- Multiple Inheritance
- Hierarchical Inheritance
- Multilevel Inheritance
- Hybrid Inheritance

Also, I want to add code for all modes of inheritance in C++.
- Public Inheritance
- Protected Inheritance
- Private Inheritance

**Comment by Saviour1001** [comment]
@pushpakumari5117 it sounds like a great idea, but we only are allowing one file per PR, so I would suggest breaking down your statement into multiple issues and PRs. Make one issue for single inheritance, another one for multiple and so on, 
And only change one file per PR. I am closing this issue. you could get started with this idea by raising multiple issues one by one. 
Happy Coding.
