### ISSUE TITLE
A CPP Solution for Allocate minimum number of pages  [GFG-Hard]

### ISSUE THREAD

**Issue by geekySapien** [smv1999/CompetitiveProgrammingQuestionBank#307]
# Description

I would like to add a C++ Solution for Allocate minimum number of pages.
I will also add all required and necessary comments so the code becomes easy to understand and interpret.

# Problem Description
You are given N number of books. Every ith book has Ai number of pages. 
You have to allocate books to M number of students. There can be many ways or permutations to do so. In each permutation, one of the M students will be allocated the maximum number of pages. Out of all these permutations, the task is to find that particular permutation in which the maximum number of pages allocated to a student is minimum of those in all the other permutations and print this minimum value. 

Each book will be allocated to exactly one student. Each student has to be allocated at least one book.

Note: Return -1 if a valid assignment is not possible, and allotment should be in contiguous order (see the explanation for better understanding).

# Sample Test Cases

## Test Case 1

![image](https://user-images.githubusercontent.com/80349103/125191045-1611ca80-e25e-11eb-988c-b08f344cabff.png)

## Test Case 2

![image](https://user-images.githubusercontent.com/80349103/125191074-32156c00-e25e-11eb-9d08-8352bedc3ce3.png)

# Problem Link: [Link](https://practice.geeksforgeeks.org/problems/allocate-minimum-number-of-pages0937/1)

@smv1999 I would like to work on this issue. Please assign me this issue.

**Comment by Saviour1001** [comment]
Add the solution !! Please provide comments in your code as well to understand it better.

**Comment by geekySapien** [comment]
Sure Sir !!
