### ISSUE TITLE
Wave Sort 

### ISSUE THREAD

**Issue by ishan-pf** [smv1999/CompetitiveProgrammingQuestionBank#308]
**Is your feature request related to a problem? Please describe.**
Wave Sort in CPPP
A clear and concise description of what the problem is. 
it's a famous interview questions where sorting is under like wave.
**Describe the solution you'd like**
In this sorting , arr[0] >arr[1] <arr[2] , this pattern is followed.
**Additional context**

**Comment by smv1999** [comment]
Sure @ishan-pf, you can go ahead !
