### ISSUE TITLE
Regarding Addition of Two New Folders to the Repository

### ISSUE THREAD

**Issue by geekySapien** [smv1999/CompetitiveProgrammingQuestionBank#309]
**Is your feature request related to a problem? Please describe.**
I would like to suggest that two folders can be created in the repository as follows:

1. Linked List
2. Searching and Sorting

Although the folders for searching and sorting do exist, but they contain all standard algorithms. A new folder can be created for "Searching and Sorting" Problems so as to enhance repository with important problems on the above topics.

**Describe the solution you'd like**
If those two folders could be added,  we can add problems from various competitive programming platforms like CodeChef and LeetCode which would also help from Interview Perspective

**Additional context**

**Comment by smv1999** [comment]
@geekySapien , LinkedList folder is already present inside Data Structures. And creation of "Searching and Sorting" would be redundant. Instead, the existing folders can be used. 

Please create a separate issue for the problem that you want to solve and mention the language also.

**Comment by geekySapien** [comment]
Okay Sir, I  got it. Thank you for the Clarification.
