### ISSUE TITLE
Dynamic Programming Problems

### ISSUE THREAD

**Issue by AbhiC7721** [smv1999/CompetitiveProgrammingQuestionBank#310]
## Is your feature request related to a problem? Please describe.
I would like to add some more dynamic programming problems

Some important questions related to dynamic programming can be added and these are the questions frequently asked in interviews 

## Describe the solution you'd like
These problems will be helpful from interview perspective. They will be leetcode or codeforces questions

**Comment by Saviour1001** [comment]
@AbhiC7721 sure you are welcome to add more DP questions. One request would be to raise a new issue and specify only one question which you want to add. As we only allow one question per issue/PR. If you want to add multiple questions please raise multiple issues and also specify the language you will be coding it in. 
Happy coding!
