### ISSUE TITLE
Find and Replace Pattern in CPP

### ISSUE THREAD

**Issue by Anupam-Panwar** [smv1999/CompetitiveProgrammingQuestionBank#312]
**Is your feature request related to a problem? Please describe.**
I would like to add [Find and Replace Pattern](https://leetcode.com/problems/find-and-replace-pattern/) of Leetcode(Medium)

**Describe the solution you'd like**
I would like to code the solution of this question in cpp

**Comment by Saviour1001** [comment]
Sure go ahead!!
