### ISSUE TITLE
Smallest window in a string containing all the characters of another string(duplicates also)

### ISSUE THREAD

**Issue by vishvarana** [smv1999/CompetitiveProgrammingQuestionBank#317]
Problem definition : https://practice.geeksforgeeks.org/problems/smallest-window-in-a-string-containing-all-the-characters-of-another-string-1587115621/1

Will give solution in c++ language

**Comment by vishvarana** [comment]
Please assign this problem to me under DCP'21 program

**Comment by smv1999** [comment]
Sure @vishvarana, you can go ahead !

**Comment by vishvarana** [comment]
Created a pull request regarding this issue
#567 
I am not able to create a new pull request hence added the file in the same PR.

**Comment by vishvarana** [comment]
New PR raised
#651 
Please review
