### ISSUE TITLE
Partition Subset Sum in Python

### ISSUE THREAD

**Issue by bhagyashree-06** [smv1999/CompetitiveProgrammingQuestionBank#319]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
Yes, it is a new feature. It is a medium level Partition Subset Sum from Geeks for Geeks

**Describe the solution you'd like**
I would like to add my solution using Backtracking concept

**Additional context**
Please assign this issue to me

**Comment by smv1999** [comment]
Sure @bhagyashree-06, you can go ahead !
