### ISSUE TITLE
Combinational Sum in Python

### ISSUE THREAD

**Issue by bhagyashree-06** [smv1999/CompetitiveProgrammingQuestionBank#320]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
Yes, it is a new feature

**Describe the solution you'd like**
It is a backtracking problem and I would like to add my solution

**Additional context**
Please assign this issue to me

**Comment by smv1999** [comment]
Sure @bhagyashree-06, you can go ahead !
