### ISSUE TITLE
OOPS : SINGLE INHERITANCE

### ISSUE THREAD

**Issue by pushpakumari5117** [smv1999/CompetitiveProgrammingQuestionBank#321]
**@Saviour1001 @smv1999 
PLEASE GO THROUGH THIS IDEA ONCE AND ASSIGN IT TO ME UNDER THE DCP21 LABEL, IT WILL BE A GREAT CONTRIBUTION TO YOUR OOPS FOLDER.**

**DESCRIPTION :**
I want to add code for Single Inheritance in C++.

**Comment by Saviour1001** [comment]
Sure go ahead, and you don't need to tag any specific mentor, any mentor who is free from his/her chores will look into the issue.
