### ISSUE TITLE
To Check if a sentence is Pangram

### ISSUE THREAD

**Issue by mrunmayee9601** [smv1999/CompetitiveProgrammingQuestionBank#324]
Given a sentence consisting of only lowercase characters, return true if sentence is pangram otherwise false. (Leetcode Problem)
Constraints-
1)1 <= sentence.length <= 1000
2)sentence consists of lowercase English letters.
I would like to build a solution for this problem in Java language.
@smv1999 Pls assign this issue to me.

**Comment by smv1999** [comment]
Sure @mrunmayee9601, you can go ahead !
