### ISSUE TITLE
OOPS : PRIVATE INHERITANCE

### ISSUE THREAD

**Issue by pushpakumari5117** [smv1999/CompetitiveProgrammingQuestionBank#329]
**@Saviour1001 @smv1999 
PLEASE GO THROUGH THIS IDEA ONCE AND ASSIGN IT TO ME UNDER THE DCP21 LABEL, IT WILL BE A GREAT CONTRIBUTION TO YOUR OOPS FOLDER.**

**DESCRIPTION :**
I want to add code for Private Inheritance in C++.

**Comment by Saviour1001** [comment]
Good to go
