### ISSUE TITLE
Points nearest to the central point .

### ISSUE THREAD

**Issue by Mayuri-cell** [smv1999/CompetitiveProgrammingQuestionBank#331]
Problem statement : 
To find the nearest distance and the points nearer to the central point .
User will enter the points and central point between which you want to find a distance. 
I will do this in c++ using arrays .

Please assign it to me under DCP'21.

**Comment by Mayuri-cell** [comment]
Please assign this issue to me under DCP'21 .

**Comment by smv1999** [comment]
Sure @Mayuri-cell, you can go ahead !

**Comment by Mayuri-cell** [comment]
closes #331
