### ISSUE TITLE
Find the prime numbers present in the range .

### ISSUE THREAD

**Issue by Mayuri-cell** [smv1999/CompetitiveProgrammingQuestionBank#333]
Problem Statement : 
Find the total prime numbers will be there till the given number provided by the user .

I will do this in java .
Please assign it to me under DCP'21 .

**Comment by Mayuri-cell** [comment]
Please assign it to me under DCP'21 .

**Comment by smv1999** [comment]
Sure @Mayuri-cell, you can go ahead !

**Comment by 889-dj** [comment]
Hey @smv1999  I would like to provide the solution in C++
