### ISSUE TITLE
Container With Most Water in CPP

### ISSUE THREAD

**Issue by Anupam-Panwar** [smv1999/CompetitiveProgrammingQuestionBank#336]
**Is your feature request related to a problem? Please describe.**
I would like to add [Container With Most Water](https://leetcode.com/problems/container-with-most-water/) of Leetcode(Medium)

**Describe the solution you'd like**
I would like to code the solution of this question in cpp

**Comment by smv1999** [comment]
Sure @Anupam-Panwar, you can go ahead !
