### ISSUE TITLE
OOPS - Method Overloading in java

### ISSUE THREAD

**Issue by KeerthanaPravallika** [smv1999/CompetitiveProgrammingQuestionBank#340]
Can you please assign me this issue under the DevIncept program

**Comment by smv1999** [comment]
Sure @KeerthanaPravallika, you can go ahead!

**Comment by KeerthanaPravallika** [comment]
I have done pull request having 3 issues, so I was creating different pull requests for each one, due to our exams there was a delay in creating PR, can you please reopen this issue.
