### ISSUE TITLE
Add Odd Even Linked List Question of Leetcode

### ISSUE THREAD

**Issue by Anupam-Panwar** [smv1999/CompetitiveProgrammingQuestionBank#346]
**Is your feature request related to a problem? Please describe.**
I would like to add [Odd Even Linked List](https://leetcode.com/problems/odd-even-linked-list/) of Leetcode(Medium)

**Describe the solution you'd like**
I would like to code the solution of this question in cpp

**Comment by Anupam-Panwar** [comment]
@Saviour1001 May you please add other appropriate labels to this issue

**Comment by Saviour1001** [comment]
Done, and BTW the labels on Issues don't matter, they are just there for the mentors and admin's reference. The labels on PRs matter.

**Comment by Anupam-Panwar** [comment]
> Done, and BTW the labels on Issues don't matter, they are just there for the mentors and admin's reference. The labels on PRs matter.

Thank you @Saviour1001. 
Is there any way this process of adding appropriate labels can also be automated by using checkbox type of thing in Issue template 

It will then be convenient for project Admin and mentor also.

**Comment by Saviour1001** [comment]
@Anupam-Panwar The current workflows give the tags of DCP21 and assigns you the issues. As the levels tags and language tags are given to PRs by the admins only, so we thought of having this system. Still will tinker on your thoughts and will upgrade.
