### ISSUE TITLE
Max XOR of Two Array

### ISSUE THREAD

**Issue by neha030** [smv1999/CompetitiveProgrammingQuestionBank#347]
Given an integer array nums, return the maximum result of nums[i] XOR nums[j], 
where 0 ≤ i ≤ j < n. 

 Enter the vector size
 6
 Enter the elements in the vector
 3 10 5 25 2 8
 The Maximum XOR of two numbers in the array/vector is : 28

I want to add the C++ code for this in Array Folder
Please assign me this issue under DCP'21

**Comment by smv1999** [comment]
Sure @neha030, you can go ahead !
