### ISSUE TITLE
Minimum XOR Value

### ISSUE THREAD

**Issue by neha030** [smv1999/CompetitiveProgrammingQuestionBank#348]
Given an integer array A of N integers, find the pair of integers 
in the array which have minimum XOR value. 

Explanation: According to the problem, we are given the size of the array 
and the numbers present in it. So we have to find two such numbers that are 
the elements of the array and their xor is the minimum in value in comparison 
to all the possible pairs of the array.

Sample Input :
Enter the size of array : 4
Enter the array : 0 2 5 7
Output 
The Minimum xor value is : 2
The corresponding elements are : 0 and 2

I want to add the C++ code for this in Array Folder
Please assign me this issue under DCP'21

**Comment by smv1999** [comment]
Sure @neha030, you can go ahead !
