### ISSUE TITLE
Intersection of 2 linked list using CPP

### ISSUE THREAD

**Issue by sr-sweta** [smv1999/CompetitiveProgrammingQuestionBank#351]
Leetcode intersection of 2 linked list code using c++.

**Comment by inimitable034** [comment]
I can solve this problem

**Comment by harshita9621** [comment]
Can I work on this issue using C++

**Comment by smv1999** [comment]
Sure @sr-sweta, you can go ahead !

**Comment by smv1999** [comment]
@inimitable034 and @harshita9621 please create new issues.
