### ISSUE TITLE
Binary Tree Maximum Path Sum using CPP 

### ISSUE THREAD

**Issue by sr-sweta** [smv1999/CompetitiveProgrammingQuestionBank#353]
Leetcode problem binary tree maximum path sum code using C++.

**Comment by harshita9621** [comment]
Can I work on this issue using C++.

**Comment by sr-sweta** [comment]
You can choose other problems as I have already solved it in a very
efficient way. Only I have to push it.

**Comment by smv1999** [comment]
Go ahead @sr-sweta
