### ISSUE TITLE
Adding Armstrong Number code in numbers section

### ISSUE THREAD

**Issue by suprithars111** [smv1999/CompetitiveProgrammingQuestionBank#359]
## Description

In recreational number theory, a narcissistic number is also known as a pluperfect digital invariant (PPDI), an Armstrong number or a plus perfect number is a number that is the sum of its digits each raised to the power of the number of digits.

**Comment by suprithars111** [comment]
@smv1999 Can I work on this in CPP?

**Comment by smv1999** [comment]
Sure
