### ISSUE TITLE
Warshall algorithm 

### ISSUE THREAD

**Issue by Khushi-agarwal** [smv1999/CompetitiveProgrammingQuestionBank#363]
**Is your feature request related to a problem? Please describe.**

It is a shortest path algorithm and I want to implement it in python language.
Kindly assign me this issue under DCP'21

**Comment by swathi-469** [comment]
I would like to work on this issue ...please assign this to me . I would do it in c language

**Comment by Khushi-agarwal** [comment]
@smv1999 please assign me .

**Comment by harshita9621** [comment]
@smv1999 Can I work using C++

**Comment by smv1999** [comment]
@swathi-469 and @harshita9621, please create a new issue for the same
