### ISSUE TITLE
Kadane's Algorithm in Java

### ISSUE THREAD

**Issue by shraddhamishra611** [smv1999/CompetitiveProgrammingQuestionBank#365]
Given an array arr of N integers. Find the contiguous sub-array with the maximum sum.
N = 5
arr[] = {1,2,3,-2,5}
Max subarray sum is 9 of elements (1, 2, 3, -2, 5) which is a contiguous subarray.

I would like to code in Java.
Please assign me this issue @smv1999

**Comment by smv1999** [comment]
The problem is already present [here](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/Arrays/largest_sum_subarray.java)
