### ISSUE TITLE
CODE_OF_CONDUCT

### ISSUE THREAD

**Issue by swathi-469** [smv1999/CompetitiveProgrammingQuestionBank#368]
I would like to add code of conduct file . Please assign this to me

**Comment by smv1999** [comment]
Please be as specific as possible. What would you like to add ?

**Comment by swathi-469** [comment]
Guidelines to be followed , Scope of the program , pledge ,  warning , standards with detailed description

**Comment by Saviour1001** [comment]
@swathi-469 If you could improvise the current state of the guidelines with much more detailed descriptions and adding images and stuff wherever necessary please go for it. 
One project can never run out of good documentation! But please make sure you are not changing too many files in one PR. As it gets hard to review. Work on one file at a time, and make separate issues if you want to contribute to multiple files.

**Comment by swathi-469** [comment]
Yeah sure

**Comment by swathi-469** [comment]
I have made my pull request please look over it
