### ISSUE TITLE
Divide and Conquor

### ISSUE THREAD

**Issue by sejal1126** [smv1999/CompetitiveProgrammingQuestionBank#373]
Hey! 
I have gone through the Divide and Conquor part and I decided to do contribution in that repo.
I will add certain program using c++.
1.Binary search
2.Finding maximum and minimum element in array.
3.Power of n element.
4.Merge sort
5.Quick sort.
6.Continuos maximum subarray sum.

please assign me this issue.

**Comment by sejal1126** [comment]
Please assign me this issue.

**Comment by smv1999** [comment]
Please create a separate issue for the same. And also check whether the problems already don't exist and have not been assigned to anyone else.
