### ISSUE TITLE
Add a merge sort algorithm

### ISSUE THREAD

**Issue by TawfikYasser** [smv1999/CompetitiveProgrammingQuestionBank#4]
Hi @smv1999 

This issue to add a new cpp program [Merge Sort]

I’m very happy to contribute to this community. 

I will open a PR now.

I will add more soon.

Thanks

**Comment by smv1999** [comment]
@TawfikYasser Cool.

**Comment by TawfikYasser** [comment]
It’s just a start.
Thanks
