### ISSUE TITLE
Cycle detection in linked list using java 

### ISSUE THREAD

**Issue by inimitable034** [smv1999/CompetitiveProgrammingQuestionBank#411]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?

Yes I have read.

## Motivation

To Detect whether a linked list contains a cycle or not using javascript with a Time Complexity of O(n)

**Comment by kiruthikvishaal** [comment]
## 🚀 Feature

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?

Yes, I have read it.

## Motivation

To Detect whether a linked list contains a cycle or not using java with a Time Complexity of O(n)

**Comment by inimitable034** [comment]
Thank you sir
@Saviour1001
