### ISSUE TITLE
Red Black Tree (Insertion and Deletion operation)

### ISSUE THREAD

**Issue by HitainKakkar** [smv1999/CompetitiveProgrammingQuestionBank#417]
## 💥 Proposal

Greetings sir/Mam,
I have contributed the code for this issue in C++/CPP.
I have added the code , along with proper explanation of the algorithm , test cases , time complexity and space complexity of the same, as per the guidelines.

This is regarding DCP21.

I have also made a pull request for the same. #418 
Kindly Check and merge.

Regards,
Hitain Kakkar
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?

YES

**Comment by Saviour1001** [comment]
@HitainKakkar please have the courtesy to read the commands given by the bots as well, you are not allowed to make PRs on the issues you are not assigned. The workflow should be assigning one issue and then solving. you could self assign  using the comment `/assign`

**Comment by HitainKakkar** [comment]
Ok!!
I'll keep in mind the next time!!
