### ISSUE TITLE
Recursion -  (Backtracking)

### ISSUE THREAD

**Issue by harshita9621** [smv1999/CompetitiveProgrammingQuestionBank#419]
/assign

### Rat In a Maze

- Problem: Given a maze(2D matrix) with obstacles, starting from (0,0) you have to
reach (n-1, n-1). If you are currently on (x,y), you can move to (x+1,y) or (x,y+1).
You can not move to the walls.
Idea: Try all the possible paths to see if you can reach (n-1,n-1)

### Input:

0 denotes wall, 1 denotes free path
two numbers n, m
Next n lines contain m numbers (0 or 1)

### Output:

Print 1 if rat can reach (n-1,m-1)
Print 0 if it can not reach (n-1,m-1)
Test Case 1:
- Input:
5 5
1 0 1 0 1
1 1 1 1 1
0 1 0 1 0
1 0 0 1 1
1 1 1 0 1
- Output:
1

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?

Yes

## Motivation

- I want to contribute to this repo and start exploring!

**Comment by harshita9621** [comment]
@smv1999 Can I work on this issue using C++.

**Comment by smv1999** [comment]
Go ahead !
