### ISSUE TITLE
Running Sum of 1d Array

### ISSUE THREAD

**Issue by sidparashar2001** [smv1999/CompetitiveProgrammingQuestionBank#439]
Is your feature request related to a problem? Please describe.
Running Sum of 1d Array is the best question for those who are at beginning or at intermediate level in solving Arrays Problem.

Describe the solution you'd like
To give a more optimal solution I will use vector to solve the problem. The code will be submitted in c++ language with the description of each and every step in the comments.

**Comment by smv1999** [comment]
Please mention the language @sidparashar2001

**Comment by sidparashar2001** [comment]
@smv1999 mentioned now
