### ISSUE TITLE
Add a String based problem from Binary Search coding platform

### ISSUE THREAD

**Issue by kiruba-r11** [smv1999/CompetitiveProgrammingQuestionBank#44]
**Is your feature request related to a problem? Please describe.**
Add a problem based on String, named `Stuck Keyboard` from the `Binary Search` platform.
[Problem Link](https://binarysearch.com/problems/Stuck-Keyboard)

**Describe the solution you'd like**
I would like to add this problem which is a coded solution in C++. Also, if required I can add it in Python too.

**Comment by smv1999** [comment]
Yes @kiruba-r11 ! You can go ahead and add solution both in C++ and Python.
