### ISSUE TITLE
Unbounded Knapsack(DP) in C++

### ISSUE THREAD

**Issue by RAUNAK-PANDEY** [smv1999/CompetitiveProgrammingQuestionBank#441]
## 🚀 Feature

Unbounded Knapsack (Knapsack with Duplicate Items )using C++ .

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?

Yes.
## Motivation

I would like to add C++ solution to this problem.

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

**Comment by Saviour1001** [comment]
Can't trust bots I guess!! You are good to go !!
