### ISSUE TITLE
Python solution for Mirror Tree

### ISSUE THREAD

**Issue by dsrao711** [smv1999/CompetitiveProgrammingQuestionBank#453]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

Link for the problem : https://practice.geeksforgeeks.org/problems/mirror-tree/1/

**Comment by dsrao711** [comment]
Please assign me this issue

**Comment by smv1999** [comment]
Go ahead !
