### ISSUE TITLE
Detect negative weight cycle

### ISSUE THREAD

**Issue by Karnika06** [smv1999/CompetitiveProgrammingQuestionBank#455]
# Aim

We are given a directed graph. We need to detect whether the graph has a negative cycle or not. A negative cycle is one in which the overall sum of the cycle becomes negative.

# Details

- I will be solving this problem using Bellman Ford's Algorithm.
- Bellman Ford algorithm is a algorithm which help us to find the shortest path from a starting vertex to all other vertices of a weighted graph.

I would like to work on this problem using C++ language.
Please assign this issue to me under DCP21.

**Comment by smv1999** [comment]
Place it in Data Structures / Graphs folder.
