### ISSUE TITLE
Inserting elements at the beginning of Linked List

### ISSUE THREAD

**Issue by Ankkkitt** [smv1999/CompetitiveProgrammingQuestionBank#458]
## 💥 Proposal

I want to add a solution of inserting elements at beginning of the linked list using C++ language. 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?

YES.

**Comment by smv1999** [comment]
Already present [here](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/tree/master/Data%20Structures/Linked%20Lists/Singly%20Linked%20List)
