### ISSUE TITLE
Merge Two Sorted Linked Lists in CPP

### ISSUE THREAD

**Issue by suprithars111** [smv1999/CompetitiveProgrammingQuestionBank#465]
Merge Two Sorted Linked Lists in CPP from leetcode.

**Comment by suprithars111** [comment]
@smv1999  Can I please work on this issue if it's not present. If yes let me know in which folder should I add.

**Comment by smv1999** [comment]
It is already present [here](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/Data%20Structures/Linked%20Lists/Singly%20Linked%20List/merge_two_sorted_linkedlist.cpp).
