### ISSUE TITLE
Length of longest substring without repeating characters(Leetcode 3)

### ISSUE THREAD

**Issue by nidhisethi88** [smv1999/CompetitiveProgrammingQuestionBank#467]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?

(Write your answer here.) yes
[lengthOfLongestSubstring.docx](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/files/6811552/lengthOfLongestSubstring.docx)

## Motivation
It is one of the most askes questions during interviews.
(Please outline the motivation for the proposal.)

## Pitch
It should be added because I have used the most optimised approach I have found till date to solve this question.
(Please explain why this feature should be implemented and how it would be used.)
It can be used by coding enthusiasts.

**Comment by nidhisethi88** [comment]
Can I work on this issue in C++?

**Comment by smv1999** [comment]
Sure @nidhisethi88, go ahead ! Place the solution in Strings folder.
