### ISSUE TITLE
Add a string based problem from LeetCode

### ISSUE THREAD

**Issue by kiruba-r11** [smv1999/CompetitiveProgrammingQuestionBank#47]
**Is your feature request related to a problem? Please describe.**
Add a string based problem, named `Reverse Vowels of a String` from `LeetCode`
[Problem Link](https://leetcode.com/problems/reverse-vowels-of-a-string/)

**Describe the solution you'd like**
I would like to solve it in C++

**Comment by smv1999** [comment]
You may go ahead @kiruba-r11 !
