### ISSUE TITLE
Add Matrix Problems

### ISSUE THREAD

**Issue by dhanashreeg368** [smv1999/CompetitiveProgrammingQuestionBank#474]
I am contributing as a part of DCP' 21. 

I wish to create a new folder for Matrix questions.  Will add programs in C++ language.
Programs to be added are -
1. Addition of two Matrices 
2.  Subtraction of two Matrices 
3.  Multiplication of two Matrices
4.  Determinant of Matrix
5.  Transpose of Matrix
6. Spirally traversing a matrix
7.  Rotate matrix by 90 degrees with extra space
8. Rotate matrix by 90 degrees without extra space

Please assign me this issue.

**Comment by smv1999** [comment]
Some of the programs are already present [here](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/tree/master/2D%20Arrays). Also, do not create a new folder Matrix problems, instead place them in 2D Arrays folder itself. And create separate issues (for each problem) for the same.
