### ISSUE TITLE
Add Queue Data Structure problems 

### ISSUE THREAD

**Issue by drishtibaranwal** [smv1999/CompetitiveProgrammingQuestionBank#475]
I am contributing as a part of DCP' 21.

I wish to create a new folder for **Queue Questions** in C language. 

Programs to be added are - 

1.  Array Implementation of Queue and its operations like enqueue, dequeue etc.
2. Circular Queue and its operations  like enqueue, dequeue etc.
3. Implementing Queue using Linked List . 

Please assign me this issue.

**Comment by smv1999** [comment]
Please create separate issues for the same. What I mean by that is create a separate issue for the 3 programs that you would like to add. It is easy to manage when each issue solves only one problem and each issue is associated to only one PR.

**Comment by drishtibaranwal** [comment]
Okk
