### ISSUE TITLE
Add StairCase Search

### ISSUE THREAD

**Issue by kiruba-r11** [smv1999/CompetitiveProgrammingQuestionBank#49]
**Is your feature request related to a problem? Please describe.**
This problem is commonly known as Search in a row and column sorted matrix. 

**Describe the solution you'd like**
I would like to solve it in C++

**Comment by smv1999** [comment]
@kiruba-r11 The description of the problem seems similar to the one that is already [here](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/2D%20Arrays/search_2d_matrix2.cpp) 
Kindly confirm that.

**Comment by kiruba-r11** [comment]
@smv1999 Yeah, they are similar. If required I could solve it in python, else I will close this issue.

**Comment by smv1999** [comment]
@kiruba-r11 Yes you can go ahead and solve it in Python.
