### ISSUE TITLE
Sort a Stack Recursion

### ISSUE THREAD

**Issue by paurush11** [smv1999/CompetitiveProgrammingQuestionBank#492]
## 📚 Documentation

(A clear and concise description of what the issue is.)
Sort a stack 
Easy Accuracy: 50.51% Submissions: 46307 Points: 2
Given a stack, the task is to sort it such that the top of the stack has the greatest element.

Example 1:

Input:
Stack: 3 2 1
Output: 3 2 1
Example 2:

Input:
Stack: 11 2 32 3 41
Output: 41 32 11 3 2
Your Task: 
You don't have to read input or print anything. Your task is to complete the function sort() which sorts the elements present in the given stack. (The sorted stack is printed by the driver's code by popping the elements of the stack.)

Expected Time Complexity : O(N*N)
Expected Auixilliary Space : O(N) recursive.

Constraints:
1<=N<=100

### Have you read the [Contributing Guidelines on Pull Requests]
Yes

**Comment by smv1999** [comment]
Problem is already present [here](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/Data%20Structures/Stacks/Sort_stack_using_recursion.cpp). Also, always mention the language in which you are going to contribute.
