### ISSUE TITLE
Find Sum of all Sub Matrices of a given Matrix 2

### ISSUE THREAD

**Issue by kiruba-r11** [smv1999/CompetitiveProgrammingQuestionBank#58]
**Is your feature request related to a problem? Please describe.**
Finding the sum of all submatrices of a given matrix and returning the total sum.

**Describe the solution you'd like**
I would like to solve this in C++. I would like to optimize the O(n ^ 6) approach I used here #55

**Comment by smv1999** [comment]
Sure @kiruba-r11. You can go ahead!
