### ISSUE TITLE
 Climbing Stairs

### ISSUE THREAD

**Issue by harshita9621** [smv1999/CompetitiveProgrammingQuestionBank#587]
/assign

## Climbing Stairs

You are climbing a staircase. It takes n steps to reach the top.

Each time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?

Yes

## Pitch

Can I work on this issue using C++.

**Comment by noviicee** [comment]
Assigned to you @harshita9621 . You can start working on it 👍

**Comment by Ayonijakaushik19** [comment]
Hi, @noviicee I have made a PR for this issue please have a look.

**Comment by harshita9621** [comment]
@Ayonijakaushik19 I am working on this issue.

**Comment by Ayonijakaushik19** [comment]
@harshita9621 it is assigned for the last 4 days but still, there is no PR for this.

**Comment by harshita9621** [comment]
Today I will PR on this issue.

**Comment by noviicee** [comment]
> Today I will PR on this issue.

Are you doing it @harshita9621 ?

**Comment by noviicee** [comment]
@Ayonijakaushik19 this issue is assigned to someone else, you can't contribute to it. Either you have to ask for assigning it to you if you see an inactivity, or could assign the non assigned issues to yourself, or create new issues. :)

**Comment by noviicee** [comment]
> > Today I will PR on this issue.
> 
> Are you doing it @harshita9621 ?

@harshita9621 you need to add a PR by today. It has been 6 days. Kindly update soon.

**Comment by harshita9621** [comment]
@Ayonijakaushik19 You can make a PR on it.
