### ISSUE TITLE
Merge two sorted arrays without using extra space

### ISSUE THREAD

**Issue by kiruba-r11** [smv1999/CompetitiveProgrammingQuestionBank#65]
**Is your feature request related to a problem? Please describe.**
Two sorted arrays would be given and those arrays should be merged without using extra space. For example:
Array - 1 = [0 , 2 , 4 , 6]
Array - 2 = [1 , 3 , 5 , 7 , 9]

Since, extra space should not be used, the result should be store in input array itself like,

Array - 1 = [0 , 1 , 2 , 3]
Array - 2 = [4 , 5 , 6 , 7 , 9]

**Describe the solution you'd like**
A coded C++ solution to merge the given two sorted arrays without using extra space.

**Comment by smv1999** [comment]
Sure @kiruba-r11 , you can go ahead!
