### ISSUE TITLE
Create readme in every folder

### ISSUE THREAD

**Issue by UG-SEP** [smv1999/CompetitiveProgrammingQuestionBank#66]
### Hey👋

I saw your repo this is just awesome i love it...
but i am thinking that there should be a **_Readme_** in each folder to clarify that folder main motive 
i.e. there should be a readme in array,2d array folder etc ..
Could I create a readme 
```javascript
if(change_given)
Thanks for giving me a chance..
I am happy 😊😊 to contribute
```
![readme missing](https://user-images.githubusercontent.com/75884061/112474665-ec5b9300-8d95-11eb-96ce-f0e469cb5dbe.jpg)
## readme is missing

**Comment by smv1999** [comment]
Sure @UG-SEP , you can go ahead !

**Comment by UG-SEP** [comment]
@smv1999  Thanks 😊

**Comment by smv1999** [comment]
@UG-SEP , On a second thought, I think that there is no need for a readme in each folder.

**Comment by UG-SEP** [comment]
ok @smv1999
