### ISSUE TITLE
A C++ Solution for Merge Without Using Extra Space 

### ISSUE THREAD

**Issue by geekySapien** [smv1999/CompetitiveProgrammingQuestionBank#695]
## 💥 Proposal

Problem Statement: Given two sorted arrays arr1[] of size N and arr2[] of size M. Each array is sorted in non-decreasing order. Merge the two arrays into one sorted array in non-decreasing order without using any extra space.

Problem Statement Link : [Link](https://practice.geeksforgeeks.org/problems/merge-two-sorted-arrays-1587115620/1)

Sample Test Cases

Test Case 1

![image](https://user-images.githubusercontent.com/80349103/126482753-c237b3ad-0a01-4d50-ad1d-3574aad1b5a8.png)

Test Case 2

![image](https://user-images.githubusercontent.com/80349103/126482789-00e35e9b-0663-4b8f-baab-927083edbcab.png)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?

Yes

**Comment by Ayonijakaushik19** [comment]
Hi, @smv1999 I have made a PR for this issue please have a look.
