### ISSUE TITLE
Find the node with minimum value in a Binary Search Tree

### ISSUE THREAD

**Issue by ManavArora26** [smv1999/CompetitiveProgrammingQuestionBank#70]
**Is your feature request related to a problem? Please describe.**
I want to add a new question with answer in Data Structures under Tree

**Describe the solution you'd like**
I would like to code this in cpp

**Describe alternatives you've considered**
i can also code this in c

**Comment by smv1999** [comment]
Sure @ManavArora26 , you can go ahead!

**Comment by ManavArora26** [comment]
@smv1999 please review!
