### ISSUE TITLE
Subarray

### ISSUE THREAD

**Issue by harshita9621** [smv1999/CompetitiveProgrammingQuestionBank#701]
## Subarray

- Subarray is a continuous part of the array.

Note: Number of subarrays of an array with n elements = nC2 + n = n*(n+1) / 2.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?

Yes

**Comment by harshita9621** [comment]
@smv1999 Can I work on this issue?

**Comment by harshita9621** [comment]
Can I work on this issue

**Comment by harshita9621** [comment]
@smv1999 Can I work on this issue?

**Comment by inimitable034** [comment]
I can solve this issue please assign me

**Comment by harshita9621** [comment]
@smv1999 Can I work on this issue because I ask from 5days

**Comment by smv1999** [comment]
You can very well assign it to yourself using the '/assign' command. But anyway, you can go ahead @harshita9621

**Comment by smv1999** [comment]
Also, could you be more specific about the problem that you are trying to solve ?

**Comment by smv1999** [comment]
@inimitable034 Please create a new issue if you want to contribute in a different language ?

**Comment by inimitable034** [comment]
> @inimitable034 Please create a new issue if you want to contribute in a different language ?
ok
