### ISSUE TITLE
The Minion Game | HackerRank

### ISSUE THREAD

**Issue by sravanyabendi** [smv1999/CompetitiveProgrammingQuestionBank#724]
Kevin and Stuart want to play the 'The Minion Game'.

Game Rules

Both players are given the same string S .
Both players have to make substrings using the letters of the string S.
Stuart has to make words starting with consonants.
Kevin has to make words starting with vowels.
The game ends when both players have made all possible substrings.

Scoring
A player gets +1 point for each occurrence of the substring in the string S.

**Comment by smv1999** [comment]
Always mention the language in which you want to contribute.
