### ISSUE TITLE
Remove duplicate 

### ISSUE THREAD

**Issue by siddhi-244** [smv1999/CompetitiveProgrammingQuestionBank#728]
## 🚀 Feature
Problem Statement: Remove Duplicates 
Problem Level: EASY
Problem Description:
Given a string S, remove consecutive duplicates from it recursively.
Input Format :
String S

Output Format :
Output string

Constraints :
1 <= |S| <= 10^3
where |S| represents the length of string

Sample Input 1 :
aabccba

Sample Output 1 :
abcba

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?
Yes
(Write your answer here.)

## Motivation

(Please outline the motivation for the proposal.)

## Pitch
I think it's a basic question from recursion which can used to understand recursion 
(Please explain why this feature should be implemented and how it would be used.)

**Comment by siddhi-244** [comment]
@smv1999 please review my pr!

**Comment by smv1999** [comment]
Always mention the language in which you want to contribute.

**Comment by siddhi-244** [comment]
> Always mention the language in which you want to contribute.

I have made a pr plzz review it.

**Comment by smv1999** [comment]
Yeah, that is being done. Generally, always make sure you mention the language in the issue.
