### ISSUE TITLE
Python solution for Reverse Linked List - Iterative and recursive way - DSA 450

### ISSUE THREAD

**Issue by dsrao711** [smv1999/CompetitiveProgrammingQuestionBank#740]
## 🚀 Feature

Link to the problem : https://leetcode.com/problems/reverse-linked-list/

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?

Yes

## Motivation

Implementing both recursive and iterative solution

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

**Comment by dsrao711** [comment]
Please assign me this issue

**Comment by inimitable034** [comment]
Please assign me this issue
I can solve this in 0(n) time complexity
