### ISSUE TITLE
Add solutions of codechef  JULY STARTERS  

### ISSUE THREAD

**Issue by simranquirky** [smv1999/CompetitiveProgrammingQuestionBank#742]
## 🚀 Feature

Add solutions of codechef  JULY STARTERS  in C Language

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?

Yes

The questions are named:
1. Cricket Ranking 
2.  Three Dices

**Comment by noviicee** [comment]
@simranquirky Make different issues for all different questions.
