### ISSUE TITLE
Provide solutions in Python

### ISSUE THREAD

**Issue by SarthakKeshari** [smv1999/CompetitiveProgrammingQuestionBank#75]
@smv1999 I wish to add solution to the existing questions in python. May you assign me this

**Comment by smv1999** [comment]
Sure @SarthakKeshari , you can go ahead!

**Comment by SarthakKeshari** [comment]
@smv1999 , So that you may keep a track of my proper contribution as well as my working over problems. I would like to generate an issue for every 5 questions I complete.
This will help both the ends to keep a proper track of the work submitted.
May I proceed with this idea?

**Comment by smv1999** [comment]
Sure @SarthakKeshari , sounds great!
