### ISSUE TITLE
Adding python solution Part - 1

### ISSUE THREAD

**Issue by SarthakKeshari** [smv1999/CompetitiveProgrammingQuestionBank#76]
I want to add python solution for the following question files - 
- Array Reversal.c
- CommonElements.cpp
- duplicates_in_array.cpp
- remove_duplicates_from_sorted_array.cpp
- subset_of_array.cpp

Kindly assign this issue to me @smv1999

**Comment by smv1999** [comment]
Sure @SarthakKeshari , you can go ahead!
