### ISSUE TITLE
Adding Python Solution Part - 2 

### ISSUE THREAD

**Issue by SarthakKeshari** [smv1999/CompetitiveProgrammingQuestionBank#78]
I want to add python solution for the following question files -

- factorial_of_a_number_recursion.c
- factorial_of_a_number.c
- fibonacci_series.c
- FindDivisors.cpp
- LargerNumber.cpp

Kindly assign this issue to me @smv1999

**Comment by smv1999** [comment]
Sure @SarthakKeshari , you can go ahead!
