### ISSUE TITLE
Method overriding in java

### ISSUE THREAD

**Issue by KeerthanaPravallika** [smv1999/CompetitiveProgrammingQuestionBank#804]
## 🚀 Feature

I want to contribute method overriding in java under DCP 21

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?

yes

**Comment by KeerthanaPravallika** [comment]
can you please /assign me this issue

**Comment by noviicee** [comment]
@KeerthanaPravallika I have assigned you with the issue. You can very well assign it to yourself by commenting **/assign** on the issue you create.
