### ISSUE TITLE
Python solution for Next Greater element in DSA 450

### ISSUE THREAD

**Issue by dsrao711** [smv1999/CompetitiveProgrammingQuestionBank#815]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?
(Write your answer here.)

Yes

## Motivation

(Please outline the motivation for the proposal.)

Link to the problem : https://leetcode.com/problems/next-greater-element-i/

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

Using stacks

**Comment by dsrao711** [comment]
Please assign me this issue

**Comment by smv1999** [comment]
You can always assign yourself using the command '/assign'.
