### ISSUE TITLE
Maximum Subarray Sum

### ISSUE THREAD

**Issue by sidparashar2001** [smv1999/CompetitiveProgrammingQuestionBank#840]
Maximum Subarray Sum is the best question for those who are at the beginning or at an intermediate level in solving Arrays Problem.

Describe the solution you'd like
To give a more optimal solution I will use Kadane's Algorithm to solve the problem. The code will be submitted in c++ language with the description of each and every step in the comments.

**Comment by smv1999** [comment]
The problem is already present [here](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/Arrays/Kadane's_Algorithm.cpp).
