### ISSUE TITLE
Permutation of a string-Recursion And Backtracking

### ISSUE THREAD

**Issue by harsh6768-svg** [smv1999/CompetitiveProgrammingQuestionBank#895]
## 💥 Proposal
We will prviode a simple string just want to get all the permutations of that particular string.
For eg:
input:
ABC
output:
ABC ACB BAC BCA CBA CAB

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?
Yes

**Comment by smv1999** [comment]
The same problem using backtracking has already been implemented [here](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/Strings/string_permutations.cpp)
