### ISSUE TITLE
Add Solutions in JavaScript

### ISSUE THREAD

**Issue by smv1999** [smv1999/CompetitiveProgrammingQuestionBank#90]
Solutions to the programming problems have to added in JavaScript. The current solutions exist in C, C++ and Java, and Python.

Developers are welcome to contribute! New problems along with the solutions in JavaScript can also be added.

Happy Coding!

**Comment by 0prodigy** [comment]
Can i create js solution for already solved question in different language?

**Comment by smv1999** [comment]
Sure @0prodigy , you can go ahead!

**Comment by inimitable034** [comment]
I can add code in javascript .
let me know the problem statement and assign me the issue

**Comment by smv1999** [comment]
You can create issue for the specific problems that you want to solve or create issue for adding a JS solution to the existing problems in the repo.
