### ISSUE TITLE
Python solution for Activity selection problem 

### ISSUE THREAD

**Issue by dsrao711** [smv1999/CompetitiveProgrammingQuestionBank#913]
## 💥 Proposal

Link to the problem : https://practice.geeksforgeeks.org/problems/n-meetings-in-one-room-1587115620/1

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?
Yes

**Comment by dsrao711** [comment]
Please check the PR

**Comment by dsrao711** [comment]
@smv1999

**Comment by smv1999** [comment]
Sure
