### ISSUE TITLE
Problems on Binary Search in C++

### ISSUE THREAD

**Issue by Soham2020** [smv1999/CompetitiveProgrammingQuestionBank#919]
Hi..... @smv1999
Please **assign** me to add some problems on binary search in cpp ?
Problems:

1. First and last occurrence of an element in a sorted array.
2. Count the frequency of an element in a sorted array.
3. Number of times a sorted array is rotated.
4. Find the element in an rotated sorted array.

**Comment by Soham2020** [comment]
Please review @smv1999

**Comment by DurveshKumarPal** [comment]
@smv1999 this issue is open or not??

**Comment by Soham2020** [comment]
Closing this issue
