### ISSUE TITLE
Chocolate Distribution Problem - Python

### ISSUE THREAD

**Issue by dsrao711** [smv1999/CompetitiveProgrammingQuestionBank#97]
**Is your feature request related to a problem? Please describe.**

- Python Solution for Chocolate Distribution Problem 
- Link to the question : https://practice.geeksforgeeks.org/problems/chocolate-distribution-problem3825/1

**Describe the solution you'd like**
- Consider an array A , M students and N be the size of array

- Sort the array
- Maximum and minimum are the last and first elements of the array
- Store the difference of max and min in min_diff
- Iterate through the array
- Since the difference has to be minimum , Find the minimum between min_diff and difference between A[i + M -1 ] and A[i]
and store it in min_diff
- Return min_diff

**Describe alternatives you've considered**

**Additional context**

**Comment by dsrao711** [comment]
Please assign me this issue

**Comment by smv1999** [comment]
Sure @dsrao711 , you can go ahead !
