### ISSUE TITLE
Add matrix problems in DSA 450

### ISSUE THREAD

**Issue by dsrao711** [smv1999/CompetitiveProgrammingQuestionBank#99]
**Is your feature request related to a problem? Please describe.**
Add Python Solutions of matrix problems in DSA 450 section

**Describe the solution you'd like**
Problems :
- Row with maximum ones : https://practice.geeksforgeeks.org/problems/row-with-max-1s0023/1
- Search an element in matrix : https://leetcode.com/problems/search-a-2d-matrix/

**Describe alternatives you've considered**

**Additional context**

**Comment by dsrao711** [comment]
Please assign me this issue

**Comment by smv1999** [comment]
Sure @dsrao711 , you can go ahead!
